// Append common.js, M, screen-helpers.js.
async function row(parent,label,detail='',to){const i=await inst(M.row,parent,label);const n=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Title#519:116'in n.componentProperties);n.setProperties({'Title#519:116':label});const tr=n.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Detail Text#508:54'in n.componentProperties);tr.setProperties({'Detail Text#508:54':detail});mutated.push(n.id,tr.id);if(to)action(i,to);return i;}
async function field(parent,label,value,state='Value Entered'){const g=stack(parent,label,354,4);txt(g,label,354,'Caption','Secondary');const i=await inst(M.field,g,label+' field');const n=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Value#519:17'in n.componentProperties);n.setProperties({State:state,'Value#519:17':value});mutated.push(n.id);return i;}
const review=await screen('review','Review classification',8,{id:'1097:745',footer:80,back:'back'});await heading(review.body,'Review',[['Task',2],['Goal',1]]);const rt=section(review.body,'Tasks');await task(rt,'Buy groceries','Today','No goal',{review:true});await task(rt,'Call the dentist','This Week','No goal',{review:true,key:'dentist'});const rg=section(review.body,'New goal');await goal(rg,'Guitar','New goal','music.note',null);txt(review.body,'Tap an item to edit it. Use its menus to change the schedule or linked goal.',354,'Small','Secondary');await button(review.foot,'Save 3 items','home');
const home=await screen('home','Home · everyday use',9,{id:'1097:589',tab:'Home',settings:true,summary:true,guide:'Task'});await heading(home.body,'Home',[['Task',7],['Goal',3]]);const today=section(home.body,'Today');await task(today,'Buy groceries');await task(today,'Practice chord changes','Today','Guitar',{key:'guitar'});await task(today,'Send the project update','Today','No goal',{key:'project'});const ongoing=section(home.body,'Goals');await goal(ongoing,'Guitar','No entries yet');await goal(ongoing,'Read more','No entries yet','book.closed');await goal(ongoing,'Run regularly','No entries yet','figure.run');
const tasks=await screen('tasks','Tasks · schedule groups',10,{id:'1097:823',tab:'Tasks',settings:true,guide:'Task'});await heading(tasks.body,'Tasks',[['Task',7]]);const tt=section(tasks.body,'Today');await task(tt,'Buy groceries');await task(tt,'Practice chord changes','Today','Guitar',{key:'guitar'});await task(tt,'Send the project update','Today','No goal',{key:'project'});const tw=section(tasks.body,'This Week');await task(tw,'Call the dentist','This Week','No goal',{key:'dentist'});await task(tw,'Pick a book for October','This Week','Read more',{key:'book'});const ts=section(tasks.body,'Someday');await task(ts,'Sort the balcony plants','Someday','No goal',{key:'plants'});await task(ts,'Find a running route','Someday','Run regularly',{key:'run'});
const goals=await screen('goals','Goals · consistent identity',11,{id:'1097:919',tab:'Goals',settings:true,guide:'Goal'});await heading(goals.body,'Goals',[['Goal',3]]);await goal(goals.body,'Guitar','No entries yet');await goal(goals.body,'Read more','No entries yet','book.closed');await goal(goals.body,'Run regularly','No entries yet','figure.run');
const detail=await screen('goal','Goal · timeline',12,{id:'1097:991',tab:'Goals',footer:76,navTitle:'Guitar',back:'back'});const hero=roundedCard(pad(stack(detail.body,'Goal introduction',354,12),24),'Sage',24);symbol(hero,'music.note',40,'Forest');txt(hero,'Guitar',306,'Large title');txt(hero,'No entries yet',306,'Small','Secondary');await inst(M.segmentTimeline,detail.body,'Timeline / Calendar');txt(detail.body,'No progress recorded',354,'Heading');txt(detail.body,'Record a step or add a note to start your timeline.',354,'Body','Secondary');const progress=stack(detail.foot,'Record progress',354,8,'HORIZONTAL');await button(progress,'Did something today','goal-recorded','Primary',302);await icon(progress,'square.and.pencil','goal-note');
const settings=await screen('settings','Settings · factual preferences',13,{id:'1097:1082',back:'close'});await heading(settings.body,'Settings');const processing=section(settings.body,'Processing');await row(processing,'Processing mode','Basic','ai');txt(processing,'Basic processing uses built-in rules. Add an AI model to interpret more varied input.',354,'Small','Secondary');await row(processing,'AI model','Not configured','ai');const pref=section(settings.body,'Preferences');for(const label of ['Dark appearance','Reminders']){const r=roundedCard(pad(stack(pref,label,354,12,'HORIZONTAL')), 'Surface',16);r.counterAxisAlignItems='CENTER';txt(r,label,234,'Body');await inst(M.toggle,r);}txt(pref,'Reminders appear after 3 days of inactivity.',354,'Small','Secondary');const data=section(settings.body,'Data');await row(data,'Storage','This iPhone','storage');await row(data,'Archived goals','','archive');const about=section(settings.body,'About');await row(about,'App tour','','onboarding');await row(about,'Version','1.0');
const ai=await screen('ai','AI model · setup',14,{back:'back',footer:80});await heading(ai.body,'AI model');txt(ai.body,'Connect a model that supports the OpenAI API format.',354,'Body','Secondary');await field(ai.body,'Endpoint URL','https://api.example.com/v1');await field(ai.body,'API key','••••••••••••••••');await field(ai.body,'Model ID','your-model-id');txt(ai.body,'Your provider receives the text you submit for AI processing. Your key is stored in Keychain.',354,'Small','Secondary');await button(ai.body,'Use basic processing','capture','Plain');await button(ai.foot,'Test connection','ai-connected');
const day=await screen('day','Your Day · summary',15,{back:'back'});await heading(day.body,'Your Day');txt(day.body,'Today',354,'Heading');const done=roundedCard(pad(stack(day.body,'Completed',354,16)));const dh=stack(done,'Completed count',322,8,'HORIZONTAL');txt(dh,'Completed',220,'Heading');await count(dh,'Task',2);txt(done,'Watered the plants\nPaid the electricity bill',322,'Body');const logged=roundedCard(pad(stack(day.body,'Goal activity',354,16)),'Sage');const lh=stack(logged,'Goal count',322,8,'HORIZONTAL');txt(lh,'Goal entries',220,'Heading');await count(lh,'Goal',0);txt(logged,'No goal entries today.',322,'Body','Secondary');await button(day.body,'View tasks','tasks','Secondary');
const connected=await screen('ai-connected','AI model · test succeeded',16,{back:'back',footer:80});await heading(connected.body,'AI model');const ok=roundedCard(pad(stack(connected.body,'Connection status',354,12)),'Sage');symbol(ok,'checkmark.circle.fill',32,'Forest');txt(ok,'Connection successful',322,'Heading');txt(ok,'The model responded to the test request.',322,'Body','Secondary');await row(connected.body,'Processing mode','AI model');await row(connected.body,'Model','your-model-id');await button(connected.foot,'Use this model','capture-ai');
const captureAI=await screen('capture-ai','Brain Dump · AI enabled',17,{tab:'Brain Dump',settings:true,footer:76});await heading(captureAI.body,'Brain Dump');await row(captureAI.body,'AI model','Connected','ai-connected');await composer(captureAI.body);await previewGroups(captureAI.body);await button(captureAI.foot,'Review 3 items','review');
const archived=await screen('archive','Archived goals',18,{back:'back'});await heading(archived.body,'Archived goals');txt(archived.body,'No archived goals',354,'Heading');txt(archived.body,'Archived goals remain here until you restore or delete them.',354,'Body','Secondary');
const denied=await screen('voice-denied','Voice · permission recovery',19,{back:'back',footer:80});await heading(denied.body,'Microphone access');txt(denied.body,'Allow microphone and speech recognition access in iPhone Settings to record a Brain Dump.',354,'Body','Secondary');await button(denied.foot,'Type instead','typing');
return result();
