// Append common.js, M and screen-helpers.js. Preserve old screen root links.
for(const id of ['1097:515','1097:588','1097:684','1097:744','1097:822','1097:918','1097:990','1097:1081','1097:1235']){const n=await figma.getNodeByIdAsync(id);if(n&&n.parent===page){removed.push(id);n.remove();}}
async function pager(parent,active){const p=await inst(await figma.importComponentByKeyAsync('86f908c2057f0a84847974d7af118310f183a682'),parent,'Onboarding progress');const indicators=p.findAllWithCriteria({types:['INSTANCE']}).filter(n=>'Is Active'in n.componentProperties);for(let i=0;i<indicators.length;i++){indicators[i].visible=i<3;indicators[i].setProperties({'Is Active':i===active?'True':'False'});mutated.push(indicators[i].id);}p.layoutAlign='CENTER';return p;}
const intro=await screen('onboarding','Introduction · no tabs',0,{id:'1097:516',footer:144});
intro.body.itemSpacing=28;txt(intro.body,'Defog',354,'Large title');
const demo=stack(intro.body,'Example input and result',354,16);pad(demo,20);roundedCard(demo,'Lilac',24);txt(demo,'“Buy groceries today.\nI’d like to learn guitar.”',314,'Title');const d=stack(demo,'Identified items',314,8,'HORIZONTAL');await count(d,'Task',1);await count(d,'Goal',1);txt(demo,'Groceries → task\nGuitar → goal',314,'Body');
txt(intro.body,'Start with what’s\non your mind.',354,'Title');txt(intro.body,'Type or record it. Defog turns your input into tasks and goals for you to review.',354,'Body','Secondary');await pager(intro.foot,0);await button(intro.foot,'Continue','onboarding-2');await button(intro.foot,'Skip introduction','storage','Plain');
const intro2=await screen('onboarding-2','Tasks and goals',1,{footer:144,back:'back'});await heading(intro2.body,'Two ways to keep track');const a=roundedCard(pad(stack(intro2.body,'Task explanation',354,12)), 'Lilac');await count(a,'Task',1);txt(a,'Tasks are things to do.',322,'Heading');txt(a,'Choose Today, This Week or Someday. Mark a task done when you finish it.',322,'Body','Secondary');const b=roundedCard(pad(stack(intro2.body,'Goal explanation',354,12)),'Sage');await count(b,'Goal',1);txt(b,'Goals are ongoing.',322,'Heading');txt(b,'Keep notes and record progress. Link related tasks to a goal.',322,'Body','Secondary');await pager(intro2.foot,1);await button(intro2.foot,'Continue','storage');await button(intro2.foot,'Skip introduction','storage','Plain');
const storage=await screen('storage','Choose storage',2,{footer:92,back:'back'});await heading(storage.body,'Where to keep your data');txt(storage.body,'Choose a storage option. You can change it later in Settings.',354,'Body','Secondary');for(const[label,detail,glyph]of [['On this iPhone','Keep tasks and goals on this device.','iphone'],['iCloud','Sync across devices signed in to your Apple Account.','icloud']]){const c=roundedCard(pad(stack(storage.body,label,354,12)));symbol(c,glyph,30);txt(c,label,322,'Heading');txt(c,detail,322,'Body','Secondary');await button(c,label==='iCloud'?'Use iCloud':'Use this iPhone','capture-empty',label==='iCloud'?'Secondary':'Primary',322);}await pager(storage.foot,2);
const empty=await screen('capture-empty','Brain Dump · first input',3,{tab:'Brain Dump',settings:true,guide:'Input'});await heading(empty.body,'Brain Dump');await aiLink(empty.body);await composer(empty.body,{empty:true});txt(empty.body,'Tasks and goals will appear here as you type.',354,'Small','Secondary');
const typed=await screen('capture','Brain Dump · typed preview',4,{id:'1097:685',tab:'Brain Dump',settings:true,footer:76});await heading(typed.body,'Brain Dump');await aiLink(typed.body);await composer(typed.body);await previewGroups(typed.body);await button(typed.foot,'Review 3 items','review');
const typing=await screen('typing','Brain Dump · keyboard',5,{footer:52});await heading(typing.body,'Brain Dump');await composer(typing.body);await button(typing.foot,'Done','capture','Plain');const keyboard=await inst(await figma.importComponentByKeyAsync('bf2a52082f2a1eca4e3f9d91fe34c64a9410dd32'),typing.f,'Apple keyboard');typing.f.insertChild(typing.f.children.length-2,keyboard);keyboard.resize(402,332);keyboard.layoutSizingVertical='FIXED';
const voice=await screen('voice','Brain Dump · recording',6,{footer:136,navTitle:'Brain Dump'});voice.body.itemSpacing=28;voice.body.primaryAxisAlignItems='CENTER';voice.body.counterAxisAlignItems='CENTER';
const wash=fade(voice.body,'Voice gradient',354,264,'Lilac','Peach',0.15,0.8);wash.cornerRadius=32;wash.primaryAxisAlignItems='CENTER';wash.counterAxisAlignItems='CENTER';await inst(M.wave,wash,'Live waveform · static specimen');const listening=txt(wash,'Recording',300,'Button');listening.textAlignHorizontal='CENTER';
const sub=txt(voice.body,'Buy groceries today.\nCall the dentist this week.\nI’d like to learn guitar.',354,'Title');sub.textAlignHorizontal='CENTER';await button(voice.foot,'Done','transcript');await button(voice.foot,'Cancel','capture','Plain');
const transcript=await screen('transcript','Brain Dump · recorded preview',7,{tab:'Brain Dump',settings:true,footer:76});await heading(transcript.body,'Brain Dump');await aiLink(transcript.body);await composer(transcript.body,{compact:true});await previewGroups(transcript.body);await button(transcript.foot,'Review 3 items','review');
return result({regions:screens.map(s=>{const f=page.children.find(n=>n.id===s.id);return{key:s.key,id:s.id,regions:f.children.map(n=>({name:n.name,y:n.y,h:n.height}))};})});
