// Append after ../common.js. Revised shared components and a second system board.
C.Forest='#326B59';
const vars=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).filter(v=>v.variableCollectionId==='VariableCollectionId:1114:1003').map(v=>[v.name,v]));
function bindSpacing(n){if(n.type==='INSTANCE')return;for(const k of ['paddingLeft','paddingRight','paddingTop','paddingBottom','itemSpacing'])if(k in n&&vars['space/'+n[k]])n.setBoundVariable(k,vars['space/'+n[k]]);if('cornerRadius'in n&&typeof n.cornerRadius==='number'&&vars['radius/'+n.cornerRadius])n.setBoundVariable('cornerRadius',vars['radius/'+n.cornerRadius]);if('children'in n)for(const c of n.children)bindSpacing(c);}
const M={status:'1096:407',home:'1096:424',tabHome:'1096:429',tabTasks:'1096:468',tabGoals:'1096:502',icon:'1096:540',buttonPrimary:'1096:553',buttonSecondary:'1096:556',buttonPlain:'1096:559',segmentTimeline:'1096:565',segmentCalendar:'1096:588',menu:'1096:611',field:'1096:617',toggle:'1096:624',row:'1096:632',task:'1096:663',goal:'1096:680',preview:'1096:689',editor:'1096:694',entry:'1096:699'};
if(page.children.some(n=>n.name==='Revision 2 / Shared components'))throw Error('Revision component board exists');
const board=stack(page,'Revision 2 / Shared components',1400,24);board.x=2130;board.y=160;board.paddingTop=32;board.paddingBottom=32;board.paddingLeft=32;board.paddingRight=32;fill(board,'Surface');
txt(board,'Shared components · revision 2',1336,'Large title');txt(board,'30 variables · light-mode color, spacing and corners. Rounded text styles are shared with the screens. Counts describe tasks, goals or entries; they are not completion percentages.',1336,'Small','Secondary');
const grid=stack(board,'Variants',1336,32,'HORIZONTAL');const left=stack(grid,'Counts and guidance',636,20),right=stack(grid,'Navigation and menus',668,20);
const nativeTabs=await figma.getNodeByIdAsync('1025:474');await fonts(nativeTabs);const set=await figma.getNodeByIdAsync('1096:536');const labels=['Home','Tasks','Goals','Brain Dump'];
for(let index=0;index<4;index++){let c;if(index<3)c=await figma.getNodeByIdAsync(M['tab'+labels[index]]);else{c=comp('Selected=Brain Dump',402);set.appendChild(c);c.name='Selected=Brain Dump';c.resize(402,95);c.primaryAxisSizingMode='FIXED';M.tabCapture=c.id;}
 await fonts(c);for(const child of [...c.children]){removed.push(child.id);child.remove();}const i=await inst(nativeTabs,c,'Apple native control');i.resize(402,95);const tabs=i.findAllWithCriteria({types:['INSTANCE']}).filter(n=>'Label#5735:10'in n.componentProperties);
 for(let j=0;j<4;j++){tabs[j].setProperties({'Label#5735:10':labels[j],'Symbol#5735:9':figma.util.getSfSymbolCharacter(['house.fill','checkmark.circle.fill','scope','waveform'][j]),Selected:index===j?'True':'False'});mutated.push(tabs[j].id);}rounded(i,'Medium');tint(i);c.x=8;c.y=8+index*111;mutated.push(c.id);}
set.resize(418,452);mutated.push(set.id);
const goalMain=await figma.getNodeByIdAsync(M.goal);await fonts(goalMain);const instrument=goalMain.findAllWithCriteria({types:['TEXT']}).find(t=>t.name==='SF Symbol / guitars');instrument.characters=figma.util.getSfSymbolCharacter('music.note');instrument.name='SF Symbol / music.note';mutated.push(instrument.id);if(!Object.keys(goalMain.componentPropertyDefinitions).some(k=>k.startsWith('Symbol#')))prop(goalMain,instrument,'Symbol');
// Keep the task family, but give its completion and overflow actions full targets.
const task=await figma.getNodeByIdAsync(M.task);await fonts(task);for(const n of [...task.children]){removed.push(n.id);n.remove();}task.itemSpacing=4;const titleLine=stack(task,'Task title',322,8,'HORIZONTAL');titleLine.counterAxisAlignItems='CENTER';
const completion=stack(titleLine,'Complete task',44,0);completion.resize(44,44);completion.primaryAxisSizingMode='FIXED';completion.primaryAxisAlignItems='CENTER';completion.counterAxisAlignItems='CENTER';symbol(completion,'circle',24,'Plum');
const title=txt(titleLine,'Buy groceries',218,'Body');title.layoutSizingHorizontal='FILL';const titleKey=Object.keys(task.componentPropertyDefinitions).find(k=>k.startsWith('Title#'));title.componentPropertyReferences={characters:titleKey};const more=await inst(M.icon,titleLine,'More actions');nativeSymbol(more,'ellipsis');
const meta=stack(task,'Task metadata',322,8,'HORIZONTAL');for(const[name,label,w]of [['Schedule','Today',112],['Goal link','No goal',156]]){const n=await inst(M.menu,meta,name);n.resize(w,44);const inner=n.findAllWithCriteria({types:['INSTANCE']}).find(x=>'Label#488:193'in x.componentProperties);inner.setProperties({'Label#488:193':label});mutated.push(inner.id);}mutated.push(task.id);
txt(left,'Task and goal identity',636,'Heading');const counts=[];
for(const [kind,glyph,color,bg]of [['Task','checkmark.circle.fill','Plum','Lilac'],['Goal','scope','Forest','Sage']]){const c=comp('Kind='+kind,76,6,'HORIZONTAL');c.name='Kind='+kind;c.paddingLeft=10;c.paddingRight=10;c.paddingTop=6;c.paddingBottom=6;c.cornerRadius=16;fill(c,bg);c.counterAxisAlignItems='CENTER';symbol(c,glyph,20,color);prop(c,txt(c,kind==='Task'?'2':'1',24,'Button',color),'Count');counts.push(c);M['count'+kind]=c.id;}
const countSet=keep(figma.combineAsVariants(counts,left));countSet.name='AI1 / Entity count';counts.forEach((n,i)=>{n.x=8+i*96;n.y=8;});countSet.resize(192,52);countSet.description='Use beside headings and group labels. Number is a count of tasks or goals, not progress toward an invented target.';
txt(left,'Guidance accessory',636,'Heading');const guides=[];
for(const[type,copy,glyph,bg]of [['Task','Tap a task’s circle to mark it done.','checkmark.circle','Lilac'],['Goal','Record a step or add a note to a goal.','scope','Sage'],['Input','Add dates like “today” or “this week”.','calendar','Peach'],['Saved','Saved 2 tasks and 1 goal.','checkmark','Sage']]){const c=comp('Kind='+type,354,8,'HORIZONTAL');c.name='Kind='+type;c.paddingLeft=12;c.paddingRight=12;c.paddingTop=12;c.paddingBottom=12;c.cornerRadius=20;c.counterAxisAlignItems='CENTER';fill(c,bg);symbol(c,glyph,22,type==='Goal'?'Forest':'Plum');const text=txt(c,copy,242,'Small');text.layoutSizingHorizontal='FILL';prop(c,text,'Message');const close=await inst(M.icon,c,'Dismiss guidance');nativeSymbol(close,'xmark');guides.push(c);M['guidance'+type]=c.id;}
const guideSet=keep(figma.combineAsVariants(guides,left));guideSet.name='AI1 / Guidance';guides.forEach((c,i)=>{c.x=8;c.y=8+i*96;});guideSet.resize(370,392);guideSet.description='Dismissible first-use instruction or factual confirmation. One at a time above tabs. Do not repeat after dismissal; do not claim intelligence or personal achievement.';
txt(right,'Four destinations',668,'Heading');await inst(M.tabCapture,right,'Brain Dump selected');
txt(right,'Native task menus',668,'Heading');const nativeMenu=await figma.getNodeByIdAsync('1112:1320');await fonts(nativeMenu);const nativeItem=await figma.getNodeByIdAsync('1112:1051');await fonts(nativeItem);
for(const[kind,items]of [['Schedule',['Today','This Week','Someday']],['Goal',['No goal','Guitar','Reading','Running']],['More',['Delete']]]){const c=comp(kind+' menu',238,0);const n=await inst(nativeMenu,c,'Apple menu');n.findOne(x=>x.name==='Control Group').visible=false;const slot=n.findAllWithCriteria({types:['SLOT']}).find(x=>x.name==='Menu Items');for(const child of [...slot.children]){removed.push(child.id);child.remove();}for(const label of items){const row=await inst(nativeItem,slot,label);row.setProperties({'Label#5856:123':label,'Show Shortcut#5502:18':false,'Show Symbol#5856:110':kind==='More','Symbol#5856:162':figma.util.getSfSymbolCharacter(kind==='More'?'trash':'checkmark'),'Show Checkmark#5511:111':false,State:kind==='More'?'Destructive':'Default'});row.resize(222,44);mutated.push(row.id);}n.resize(238,items.length*44+16);c.resize(238,items.length*44+16);c.primaryAxisSizingMode='FIXED';right.appendChild(c);M['menu'+kind]=c.id;c.description='Attached Apple menu. Prototype supplies dismissal and menu selection routes.';}
// Recording is a static vector specimen, not generated audio or a live meter.
txt(left,'Recording indicator · static',636,'Heading');const wave=comp('Recording indicator',240,0);wave.resize(240,120);wave.primaryAxisSizingMode='FIXED';wave.primaryAxisAlignItems='CENTER';wave.counterAxisAlignItems='CENTER';const svg=keep(figma.createNodeFromSvg('<svg xmlns="http://www.w3.org/2000/svg" width="224" height="88" viewBox="0 0 224 88"><g fill="none" stroke="#7653A6" stroke-width="8" stroke-linecap="round"><path d="M20 37v14 M43 24v40 M66 34v20 M89 12v64 M112 26v36 M135 8v72 M158 29v30 M181 21v46 M204 37v14"/></g></svg>'));wave.appendChild(svg);left.appendChild(wave);M.wave=wave.id;wave.description='Static editable vector waveform. Does not claim measured audio intensity. Motion and Reduce Motion behavior are specified separately.';
for(const c of page.findAllWithCriteria({types:['COMPONENT']}))if(c.name.startsWith('AI1 / ')||c.parent===set||c.parent===guideSet||c.parent===countSet){bindSpacing(c);mutated.push(c.id);}
bindSpacing(board);for(const t of (await figma.getNodeByIdAsync('1096:368')).findAllWithCriteria({types:['TEXT']})){if(t.characters==='defog · a little room to breathe'){await fonts(t.parent);t.characters='defog · design system';mutated.push(t.id);}if(t.characters.includes('Full tab slot')){t.characters='Four persistent destinations. Full tab slot 95pt; home slot 34pt.';mutated.push(t.id);}}
return summary({boardId:board.id,boardBounds:{x:board.x,y:board.y,w:board.width,h:board.height},masters:M,countSet:countSet.id,guidanceSet:guideSet.id,tabSet:set.id});
