// Append common.js, M and screen-helpers.js.
const note=await screen('goal-note','Goal · add a note',20,{navTitle:'Guitar',back:'back',footer:80});await heading(note.body,'Add a note');const input=roundedCard(pad(stack(note.body,'Note input',354,16)));txt(input,'Practiced switching between G and C for ten minutes.',322,'Body');await button(note.foot,'Save note','goal-recorded');
const recorded=await screen('goal-recorded','Goal · recorded entry',21,{tab:'Goals',navTitle:'Guitar',back:'back'});const h=roundedCard(pad(stack(recorded.body,'Goal introduction',354,12),24),'Sage',24);symbol(h,'music.note',40,'Forest');txt(h,'Guitar',306,'Large title');txt(h,'1 entry',306,'Small','Secondary');await inst(M.segmentTimeline,recorded.body,'Timeline / Calendar');const e=roundedCard(pad(stack(section(recorded.body,'Today'),'Progress entry',354,12)));txt(e,'Practiced guitar',322,'Heading');txt(e,'Practiced switching between G and C for ten minutes.',322,'Body');
const failed=await screen('ai-failed','AI model · test failed',22,{back:'back',footer:80});await heading(failed.body,'AI model');const err=roundedCard(pad(stack(failed.body,'Connection failure',354,12)),'Peach');symbol(err,'exclamationmark.circle',32);txt(err,'Couldn’t connect',322,'Heading');txt(err,'Check the endpoint, API key and model ID, then try again.',322,'Body');await button(failed.body,'Edit connection details','ai','Secondary');await button(failed.foot,'Use basic processing','capture');
const edit=await screen('edit-task','Task · edit text',23,{navTitle:'Edit task',back:'back',footer:80});await heading(edit.body,'Task');const f=await inst(M.field,edit.body,'Task title field');const native=f.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Value#519:17'in n.componentProperties);native.setProperties({State:'Value Entered','Value#519:17':'Buy groceries'});mutated.push(native.id);await button(edit.foot,'Done','BACK');
const overlayData=[];
async function overlay(key,title,index){const f=fixed(page,'Overlay / '+key,402,874);f.x=2220+(index%3)*474;f.y=1900+Math.floor(index/3)*1050;f.fills=[];f.clipsContent=false;f.primaryAxisAlignItems='CENTER';f.counterAxisAlignItems='CENTER';const backdrop=fixed(f,'Dismiss overlay',402,874);backdrop.layoutPositioning='ABSOLUTE';backdrop.x=0;backdrop.y=0;backdrop.fills=[{type:'SOLID',color:{r:0,g:0,b:0},opacity:0.12}];action(backdrop,'CLOSE','CLOSE');const label=txt(page,title,402,'Heading');label.x=f.x;label.y=f.y-44;overlayData.push({key,id:f.id});return f;}
for(const[key,title,index]of [['menuSchedule','Task schedule menu',0],['menuGoal','Linked goal menu',1],['menuMore','Task overflow menu',2],['menuReview','Review overflow menu',3]]){const o=await overlay(key,title,index);const i=await inst(M[key==='menuReview'?'menuMore':key],o,title);i.clipsContent=false;for(const n of i.findAllWithCriteria({types:['INSTANCE']})){if('clipsContent'in n)n.clipsContent=false;if('Label#5856:123'in n.componentProperties){if(key==='menuReview')n.setProperties({'Label#5856:123':'Remove from preview'});action(n,key==='menuMore'?'delete-confirm':key==='menuReview'?'remove':n.componentProperties['Label#5856:123'].value,key==='menuMore'?'SWAP':'MENU_SELECT');mutated.push(n.id);}}}
const del=await overlay('delete-confirm','Delete confirmation',4);const alert=await inst(await figma.importComponentByKeyAsync('2c4786e8fb68860d0467444158cc967067a4e6dc'),del,'Apple delete alert');alert.setProperties({'Title#10448:7':'Delete task?','Message#10448:4':'This task will be permanently deleted.','Show Text Field#12616:4':false});for(const n of alert.findAllWithCriteria({types:['INSTANCE']})){if('Title#452:1'in n.componentProperties){const cancel=n.componentProperties.Role.value==='Cancel';n.setProperties({'Title#452:1':cancel?'Cancel':'Delete',Role:cancel?'Cancel':'Destructive'});action(n,cancel?'CLOSE':'delete',cancel?'CLOSE':'MENU_SELECT');mutated.push(n.id);}}
return result({overlays:overlayData});
