// Append common.js and M. Repair live identities after native instance property changes.
const vv=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).filter(v=>v.variableCollectionId==='VariableCollectionId:1125:2545').map(v=>[v.name,v]));
const set=(v,value)=>({type:'SET_VARIABLE',variableId:v.id,variableValue:{type:v.resolvedType,resolvedType:v.resolvedType,value}});
const alias=v=>({type:'VARIABLE_ALIAS',resolvedType:v.resolvedType,value:{type:'VARIABLE_ALIAS',id:v.id}});
const literal=(value,type)=>({type,resolvedType:type,value});
const expr=(fn,args,type='BOOLEAN')=>({type:'EXPRESSION',resolvedType:type,value:{expressionFunction:fn,expressionArguments:args}});
const iff=(condition,actions)=>({type:'CONDITIONAL',conditionalBlocks:[{condition,actions}]});
const eq=(a,b)=>expr('EQUALS',[a,b]);
const nav=id=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:true});
async function link(n,a){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:a}]);mutated.push(n.id);}
const keys=['review-groceries','review-dentist','groceries','guitar','project','dentist','book','plants','run'];
function counterUpdate(variable,display){return Array.from({length:8},(_,i)=>iff(eq(alias(variable),literal(i,'FLOAT')),[set(display,String(i))]));}
function countDown(variable){return{type:'SET_VARIABLE',variableId:variable.id,variableValue:expr('SUBTRACTION',[alias(variable),literal(1,'FLOAT')],'FLOAT')};}
for(const[id,type]of [['1122:2312','schedule'],['1122:2343','goal'],['1122:2398','remove']]){const f=await figma.getNodeByIdAsync(id);await fonts(f);for(const item of f.findAllWithCriteria({types:['INSTANCE']}).filter(n=>'Label#5856:123'in n.componentProperties)){const label=item.componentProperties['Label#5856:123'].value;const value={Reading:'Read more',Running:'Run regularly'}[label]||label;const a=keys.map(key=>iff(eq(alias(vv.activeTask),literal(key,'STRING')),type==='remove'?[set(vv['task/'+key+'/visible'],false),countDown(vv[key.startsWith('review-')?'reviewTasks':'openTasks'])]:[set(vv['task/'+key+'/'+type],value)]));if(type==='remove')a.push(...counterUpdate(vv.reviewTasks,vv.reviewTasksText),iff(eq(alias(vv.reviewTasks),literal(1,'FLOAT')),[set(vv.saveLabel,'Save 2 items')]),iff(eq(alias(vv.reviewTasks),literal(0,'FLOAT')),[set(vv.saveLabel,'Save 1 item')]));a.push({type:'CLOSE'});await link(item,a);}}
const alert=await figma.getNodeByIdAsync('1122:2433');const del=alert.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.componentProperties['Title#452:1']?.value==='Delete');await link(del,[...keys.map(key=>iff(eq(alias(vv.activeTask),literal(key,'STRING')),[set(vv['task/'+key+'/visible'],false),countDown(vv[key.startsWith('review-')?'reviewTasks':'openTasks'])])),...counterUpdate(vv.openTasks,vv.openTasksText),{type:'CLOSE'}]);
// Saving reflects removed reviewed tasks in the populated fixture without repeated decrements.
const save=await figma.getNodeByIdAsync('1119:2130');const saveActions=[];for(const key of ['groceries','dentist'])saveActions.push(iff(expr('AND',[eq(alias(vv['task/review-'+key+'/visible']),literal(false,'BOOLEAN')),eq(alias(vv['task/'+key+'/visible']),literal(true,'BOOLEAN'))]),[set(vv['task/'+key+'/visible'],false),countDown(vv.openTasks)]));saveActions.push(...counterUpdate(vv.openTasks,vv.openTasksText),nav('1097:589'));await link(save,saveActions);
for(const[title,id]of [['Read more','1129:2367'],['Run regularly','1129:2432']])for(const fId of ['1097:589','1097:919']){const f=await figma.getNodeByIdAsync(fId);const card=f.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name===title);await link(card,[nav(id)]);}
// Text editing uses the selected task's title instead of showing groceries for every item.
const editor=await figma.getNodeByIdAsync('1122:2270');await fonts(editor);const editField=editor.findAllWithCriteria({types:['TEXT']}).find(n=>n.characters==='Buy groceries');let titleVar=vv.editingTaskTitle;if(!titleVar){const collection=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:1125:2545');titleVar=figma.variables.createVariable('editingTaskTitle',collection,'STRING');titleVar.scopes=['TEXT_CONTENT'];titleVar.setValueForMode(collection.defaultModeId,'Buy groceries');}editField.setBoundVariable('characters',titleVar);mutated.push(editField.id);
for(const f of page.children.filter(n=>n.name.startsWith('Screen / ')))for(const task of f.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name.startsWith('Task / '))){await fonts(task);const t=task.findAllWithCriteria({types:['TEXT']}).find(n=>n.componentPropertyReferences?.characters?.startsWith('Title#'));if(t)await link(t,[set(titleVar,t.characters),nav(editor.id)]);}
// Quick progress records no invented note. The note example remains a separate path.
const source=await figma.getNodeByIdAsync('1122:2152');await fonts(source);const quick=keep(source.clone());page.appendChild(quick);quick.name='Screen / goal-quick-recorded';quick.x=3168;quick.y=5050;for(const t of quick.findAllWithCriteria({types:['TEXT']})){if(t.characters==='Practiced guitar'){t.characters='Progress recorded';mutated.push(t.id);}if(t.characters==='Practiced switching between G and C for ten minutes.'){t.visible=false;mutated.push(t.id);}}await link(await figma.getNodeByIdAsync('1119:2699'),[nav(quick.id)]);
return summary({quickRecorded:quick.id,editingTitleVariable:titleVar.id});
