// Append common.js, M, screen-helpers.js and const state=<screen ledgers>.
const routes=Object.fromEntries([...state.screens,...state.overlays].map(s=>[s.key,s.id]));
const prototype=(await figma.variables.getLocalVariableCollectionsAsync()).find(c=>c.name==='Defog / Prototype state')||figma.variables.createVariableCollection('Defog / Prototype state');const existingVars=await figma.variables.getLocalVariablesAsync();const variableIds=[],variableTypes={};
function v(name,type,value,scopes){const n=existingVars.find(v=>v.variableCollectionId===prototype.id&&v.name===name)||figma.variables.createVariable(name,prototype,type);n.scopes=type==='BOOLEAN'?['ALL_SCOPES']:scopes;n.setValueForMode(prototype.defaultModeId,value);variableIds.push(n.id);variableTypes[n.id]=type;return n;}
function set(n,value,type=n.resolvedType){return{type:'SET_VARIABLE',variableId:n.id,variableValue:{type,resolvedType:n.resolvedType,value}};}
function node(to,nav='NAVIGATE'){return{type:'NODE',destinationId:routes[to],navigation:nav,transition:nav==='NAVIGATE'?null:{type:'DISSOLVE',duration:.15,easing:{type:'EASE_OUT'}},resetScrollPosition:true};}
function normalize(x){if(!x||typeof x!=='object')return;if('value'in x&&['FLOAT','STRING','BOOLEAN','VARIABLE_ALIAS'].includes(x.type))x.resolvedType=x.type==='VARIABLE_ALIAS'?variableTypes[x.value.id]:x.type;for(const child of Object.values(x))if(child&&typeof child==='object')normalize(child);}
async function react(n,a){a=a.flatMap(x=>x.type==='CONDITIONAL'&&x.conditionalBlocks.length>2?x.conditionalBlocks.map(b=>({type:'CONDITIONAL',conditionalBlocks:[b]})):[x]);normalize(a);let root=n;while(root.parent&&root.parent!==page)root=root.parent;a=a.filter(x=>!(x.type==='NODE'&&x.navigation==='NAVIGATE'&&x.destinationId===root.id));if(!a.length)return;await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:a}]);mutated.push(n.id);}
const active=v('activeTask','STRING','groceries',[]);const openCount=v('openTasks','FLOAT',7,['TEXT_CONTENT']);const reviewCount=v('reviewTasks','FLOAT',2,['TEXT_CONTENT']);const saveLabel=v('saveLabel','STRING','Save 3 items',['TEXT_CONTENT']);
const openDisplay=v('openTasksText','STRING','7',['TEXT_CONTENT']);const reviewDisplay=v('reviewTasksText','STRING','2',['TEXT_CONTENT']);
const taskState={};const screenById=Object.fromEntries(state.screens.map(s=>[s.id,s]));
function screenOf(n){let p=n;while(p&&p.parent!==page)p=p.parent;return p?screenById[p.id]:null;}
function taskOf(n){let p=n;while(p&&p.parent!==page){if(p.type==='INSTANCE'&&p.name.startsWith('Task / '))return p;p=p.parent;}return null;}
function keyOf(i){const s=screenOf(i);return(s.key==='review'?'review-':'')+i.name.slice(7);}
const allTaskInstances=[];
for(const s of state.screens){const f=await figma.getNodeByIdAsync(s.id);await fonts(f);for(const i of f.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name.startsWith('Task / '))){const key=keyOf(i);if(!taskState[key]){const schedule=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name==='Schedule').findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#488:193'in n.componentProperties);const goal=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name==='Goal link').findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#488:193'in n.componentProperties);taskState[key]={visible:v('task/'+key+'/visible','BOOLEAN',true,[]),schedule:v('task/'+key+'/schedule','STRING',schedule.componentProperties['Label#488:193'].value,['TEXT_CONTENT']),goal:v('task/'+key+'/goal','STRING',goal.componentProperties['Label#488:193'].value,['TEXT_CONTENT'])};}const vars=taskState[key];i.setBoundVariable('visible',vars.visible);mutated.push(i.id);for(const[name,variable]of [['Schedule',vars.schedule],['Goal link',vars.goal]]){const wrap=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name===name);const t=wrap.findAllWithCriteria({types:['TEXT']}).find(n=>/Today|This Week|Someday|No goal|Guitar|Read more|Run regularly/.test(n.characters));if(t){t.setBoundVariable('characters',variable);mutated.push(t.id);}}
const title=i.findAllWithCriteria({types:['TEXT']}).find(n=>n.componentPropertyReferences?.characters?.startsWith('Title#'));if(title)await react(title,[node('edit-task')]);allTaskInstances.push({id:i.id,key});}
for(const c of f.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name==='Task count')){const applicable=s.key==='review'?reviewDisplay:['home','tasks'].includes(s.key)?openDisplay:null;if(applicable){const t=c.findAllWithCriteria({types:['TEXT']}).find(n=>/^\d+$/.test(n.characters));t.setBoundVariable('characters',applicable);mutated.push(t.id);}}
}
function decrement(variable){return{type:'SET_VARIABLE',variableId:variable.id,variableValue:{type:'EXPRESSION',resolvedType:'FLOAT',value:{expressionFunction:'SUBTRACTION',expressionArguments:[{type:'VARIABLE_ALIAS',value:{type:'VARIABLE_ALIAS',id:variable.id}},{type:'FLOAT',value:1}]}}};}
function removeTask(key){const review=key.startsWith('review-');const actions=[set(taskState[key].visible,false),decrement(review?reviewCount:openCount)];actions.push({type:'CONDITIONAL',conditionalBlocks:Array.from({length:8},(_,value)=>({condition:{type:'EXPRESSION',resolvedType:'BOOLEAN',value:{expressionFunction:'EQUALS',expressionArguments:[{type:'VARIABLE_ALIAS',value:{type:'VARIABLE_ALIAS',id:(review?reviewCount:openCount).id}},{type:'FLOAT',value}]}},actions:[set(review?reviewDisplay:openDisplay,String(value))]}))});if(review)actions.push({type:'CONDITIONAL',conditionalBlocks:[{condition:{type:'EXPRESSION',resolvedType:'BOOLEAN',value:{expressionFunction:'EQUALS',expressionArguments:[{type:'VARIABLE_ALIAS',value:{type:'VARIABLE_ALIAS',id:reviewCount.id}},{type:'FLOAT',value:1}]}},actions:[set(saveLabel,'Save 2 items')]},{actions:[set(saveLabel,'Save 1 item')]}]});return actions;}
const hints={};let linkCount=0;
for(const a of state.actions){const n=await figma.getNodeByIdAsync(a.id);if(!n)continue;let aa=[];
if(a.kind==='DISMISS_GUIDANCE'){const region=n.parent.parent;const key=screenOf(n).key;hints[key]??=v('guidance/'+key,'BOOLEAN',true,[]);let p=n;while(p&&p.name!=='Guidance region')p=p.parent;if(p){p.setBoundVariable('visible',hints[key]);mutated.push(p.id);}aa=[set(hints[key],false)];}
else if(a.kind==='TASK_COMPLETE'||a.kind==='REVIEW_REMOVE'){aa=removeTask(keyOf(taskOf(n)));}
else if(a.kind==='MENU_SELECT'){const value=a.to==='Reading'?'Read more':a.to==='Running'?'Run regularly':a.to;aa=[{type:'CONDITIONAL',conditionalBlocks:Object.keys(taskState).map(key=>({condition:{type:'EXPRESSION',resolvedType:'BOOLEAN',value:{expressionFunction:'EQUALS',expressionArguments:[{type:'VARIABLE_ALIAS',value:{type:'VARIABLE_ALIAS',id:active.id}},{type:'STRING',value:key}]}},actions:['delete','remove'].includes(value)?removeTask(key).filter(x=>x.type!=='CONDITIONAL'):[set(taskState[key][['Today','This Week','Someday'].includes(value)?'schedule':'goal'],value)]}))},{type:'CLOSE'}];}
else if(a.kind==='CLOSE'||a.to==='CLOSE')aa=[{type:'CLOSE'}];
else if(a.to==='BACK')aa=[{type:'BACK'}];
else if(routes[a.to]){const task=taskOf(n);if(task)aa.push(set(active,keyOf(task)));aa.push(node(a.to,a.kind==='OVERLAY'?'OVERLAY':a.kind==='SWAP'?'SWAP':'NAVIGATE'));}
if(a.kind==='MENU_SELECT'&&['delete','remove'].includes(a.to)){aa.pop();aa.push(...removeTask('groceries').filter(x=>x.type==='CONDITIONAL'),...removeTask('review-groceries').filter(x=>x.type==='CONDITIONAL'),{type:'CLOSE'});}if(aa.length){await react(n,aa);linkCount++;}
}
// Update the Save label after removing a reviewed task.
const save=await figma.getNodeByIdAsync('1119:2130');const saveText=save.findAllWithCriteria({types:['TEXT']}).find(n=>n.characters==='Save 3 items');saveText.setBoundVariable('characters',saveLabel);mutated.push(saveText.id);
// Persistent four-tab navigation, with draft content retained in this specimen.
for(const s of state.screens){const f=await figma.getNodeByIdAsync(s.id);const bar=f.children.find(n=>n.name==='Tabs');if(!bar)continue;for(const n of bar.findAllWithCriteria({types:['INSTANCE']})){const label=n.componentProperties['Label#5735:10']?.value;const to={Home:'home',Tasks:'tasks',Goals:'goals','Brain Dump':'capture'}[label];if(to&&routes[to]!==s.id){await react(n,[node(to)]);linkCount++;}}}
// Correct mode copy, preserve the actual endpoint contract, remove an unsupported storage claim.
const ai=await figma.getNodeByIdAsync(routes.ai);for(const t of ai.findAllWithCriteria({types:['TEXT']})){if(t.characters.includes('Your key is stored')){t.characters='Your provider receives the text you submit for AI processing.';mutated.push(t.id);}if(t.characters==='https://api.example.com/v1'){t.characters='https://api.example.com/v1/chat/completions';mutated.push(t.id);}}
// Use goal color consistently in reusable goal cards.
const gm=await figma.getNodeByIdAsync(M.goal);await fonts(gm);fill(gm,'Sage');mutated.push(gm.id);for(const t of gm.findAllWithCriteria({types:['TEXT']})){if(t.name.startsWith('SF Symbol')){fill(t,'Forest');mutated.push(t.id);}}
// Correct empty-composer Type destination.
await react(await figma.getNodeByIdAsync('1118:6296'),[node('typing')]);
// Keep filled previews compact enough to expose more of the classified output.
for(const key of ['capture','capture-ai','transcript']){const f=await figma.getNodeByIdAsync(routes[key]);const b=f.children.find(n=>n.name==='Scrollable content');b.itemSpacing=16;mutated.push(b.id);const composer=b.children.find(n=>n.name==='Composer');if(composer){composer.itemSpacing=8;const input=composer.children.find(n=>n.type==='TEXT'&&n.characters==='INPUT');if(input){removed.push(input.id);input.remove();}const content=composer.children.find(n=>n.type==='TEXT');content.textAutoResize='HEIGHT';mutated.push(content.id,composer.id);}}
page.flowStartingPoints=[{nodeId:routes.onboarding,name:'01 · Onboarding and first capture'},{nodeId:routes.home,name:'02 · Everyday app'},{nodeId:routes.voice,name:'03 · Voice capture'},{nodeId:routes['ai-failed'],name:'04 · Connection failure'},{nodeId:routes['voice-denied'],name:'05 · Voice permission recovery'}];mutated.push(page.id);
const previousNotes=await figma.getNodeByIdAsync('1125:2766');if(previousNotes){removed.push(previousNotes.id);previousNotes.remove();}const notes=roundedCard(pad(stack(page,'Revision 2 · review notes',1400,16),24));notes.x=2130;notes.y=1180;txt(notes,'Revision 2 · review notes',1352,'Title');txt(notes,'Try the four tabs, microphone → Done → Review → Save, task menus, dismissible guidance, Your Day, and AI setup. Task schedules, goal links, completion and deletion use prototype variables. Restart the flow to reset examples.',1352,'Body');txt(notes,'Synthetic fixtures. Text entry, recording, API connection tests, storage migration, notifications and dark mode are visual examples; Figma does not run the app. The connection-failure and permission-recovery examples have separate starting points. Full review categories and calendar behavior are still outside this revision.',1352,'Small','Secondary');
return summary({linkCount,prototypeCollection:prototype.id,variableIds,taskInstances:allTaskInstances,flowStartingPoints:page.flowStartingPoints,notesId:notes.id});
