// Append common.js. Keep schedule changes reflected in actual list grouping.
const vars=await figma.variables.getLocalVariablesAsync();const collection=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:1125:2545');
const schedules=['Today','This Week','Someday'];const states={};const taskPage=await figma.getNodeByIdAsync('1097:823');await fonts(taskPage);const body=taskPage.children.find(n=>n.name==='Scrollable content');const groups=Object.fromEntries(body.children.filter(n=>schedules.includes(n.name)).map(n=>[n.name,n]));const originals=taskPage.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name.startsWith('Task / '));
function set(variable,value){return{type:'SET_VARIABLE',variableId:variable.id,variableValue:{type:'BOOLEAN',resolvedType:'BOOLEAN',value}};}
for(const i of originals){const key=i.name.slice(7);const current=i.parent.name;states[key]={};for(const label of schedules){const v=figma.variables.createVariable('scheduleSlot/'+key+'/'+label,collection,'BOOLEAN');v.scopes=['ALL_SCOPES'];v.setValueForMode(collection.defaultModeId,label===current);states[key][label]=v;const card=label===current?i:keep(i.clone());const wrap=stack(groups[label],key+' · '+label,354,0);wrap.setBoundVariable('visible',v);wrap.appendChild(card);mutated.push(card.id);}}
const home=await figma.getNodeByIdAsync('1097:589');await fonts(home);const today=home.findOne(n=>n.type==='FRAME'&&n.name==='Today');for(const i of [...today.children].filter(n=>n.type==='INSTANCE'&&n.name.startsWith('Task / '))){const key=i.name.slice(7);const wrap=stack(today,key+' · Today',354,0);wrap.setBoundVariable('visible',states[key].Today);wrap.appendChild(i);mutated.push(i.id);}
// A native menu selection updates the schedule and the visible group slots.
const menu=await figma.getNodeByIdAsync('1122:2312');for(const item of menu.findAllWithCriteria({types:['INSTANCE']}).filter(n=>'Label#5856:123'in n.componentProperties)){const target=item.componentProperties['Label#5856:123'].value;const reactions=JSON.parse(JSON.stringify(item.reactions));for(const r of reactions){delete r.action;for(const a of r.actions||[])if(a.type==='CONDITIONAL')for(const b of a.conditionalBlocks){const key=b.condition?.value?.expressionArguments?.[1]?.value;if(states[key])b.actions.push(...schedules.map(label=>set(states[key][label],label===target)));}}await item.setReactionsAsync(reactions);mutated.push(item.id);}
// Deletion, completion, and removed preview items also collapse their list slot.
const visibleKeys=Object.fromEntries(vars.filter(v=>/^task\/(?!review-).+\/visible$/.test(v.name)).map(v=>[v.id,v.name.split('/')[1]]));
for(const root of [home,taskPage,await figma.getNodeByIdAsync('1122:2433'),await figma.getNodeByIdAsync('1097:745')]){for(const n of root.findAll(n=>'reactions'in n&&n.reactions.length)){const reactions=JSON.parse(JSON.stringify(n.reactions));let changed=false;function amend(actions){for(let i=actions.length-1;i>=0;i--){const a=actions[i];if(a.type==='CONDITIONAL')for(const b of a.conditionalBlocks)amend(b.actions);const key=a.type==='SET_VARIABLE'&&a.variableValue?.value===false?visibleKeys[a.variableId]:null;if(key&&states[key]){actions.splice(i+1,0,...schedules.map(label=>set(states[key][label],false)));changed=true;}}}for(const r of reactions){delete r.action;amend(r.actions||[]);}if(changed){await n.setReactionsAsync(reactions);mutated.push(n.id);}}}
return summary({slotVariableIds:Object.values(states).flatMap(v=>Object.values(v).map(n=>n.id)),taskInstances:taskPage.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name.startsWith('Task / ')).map(n=>n.id)});
