// Append after ../common.js and const M=<masters from components.json>.
C.Forest='#326B59';
const tokens=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).filter(v=>v.variableCollectionId==='VariableCollectionId:1114:1003').map(v=>[v.name,v]));
const screens=[],actions=[];
function action(n,to,kind='NAVIGATE'){actions.push({id:n.id,to,kind});return n;}
function fixed(parent,name,w,h,color){const n=stack(parent,name,w,0);n.resize(w,h);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';if(color)fill(n,color);return n;}
function pad(n,v=16){for(const p of ['paddingLeft','paddingRight','paddingTop','paddingBottom']){n[p]=v;if(tokens['space/'+v])n.setBoundVariable(p,tokens['space/'+v]);}return n;}
function roundedCard(n,bg='Surface',r=20){fill(n,bg);n.cornerRadius=r;if(tokens['radius/'+r])n.setBoundVariable('cornerRadius',tokens['radius/'+r]);return n;}
async function button(parent,label,to,role='Primary',width=354){const b=await inst(M['button'+role],parent,label);b.resize(width,52);nativeText(b,label);if(to)action(b,to);return b;}
async function icon(parent,glyph,to){const n=await inst(M.icon,parent,glyph);nativeSymbol(n,glyph);if(to)action(n,to);return n;}
async function count(parent,kind,value){const n=await inst(M['count'+kind],parent,kind+' count');own(n,'Count',String(value));return n;}
async function heading(parent,title,counts=[]){const row=stack(parent,'Heading',354,10,'HORIZONTAL');row.counterAxisAlignItems='CENTER';const t=txt(row,title,200,'Large title');t.layoutSizingHorizontal='FILL';for(const[k,n]of counts)await count(row,k,n);return row;}
function section(parent,title){const s=stack(parent,title,354,8);txt(s,title,354,'Heading');return s;}
function fade(parent,name,w,h,from='Surface',to='Surface',alphaTop=0,alphaBottom=1){const n=fixed(parent,name,w,h);n.fills=[{type:'GRADIENT_LINEAR',gradientTransform:[[0,1,0],[-1,0,1]],gradientStops:[{position:0,color:{...rgb(C[from]),a:alphaTop}},{position:1,color:{...rgb(C[to]),a:alphaBottom}}]}];return n;}
async function guidance(parent,kind){const region=fixed(parent,'Guidance region',402,96);const bg=fade(region,'White fade',402,96);bg.layoutPositioning='ABSOLUTE';bg.x=0;bg.y=0;region.paddingLeft=24;region.paddingRight=24;region.paddingTop=12;const g=await inst(M['guidance'+kind],region,'Guidance');action(g.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name==='Dismiss guidance'),'dismiss-guidance','DISMISS_GUIDANCE');return region;}
async function screen(key,label,index,{id=null,tab=null,footer=0,navTitle='',back=null,settings=false,summary=false,guide=null}={}){
 let f;if(id){f=await figma.getNodeByIdAsync(id);if(f.parent!==page||f.type!=='FRAME')throw Error('Unexpected screen '+id);await fonts(f);for(const child of [...f.children]){removed.push(child.id);child.remove();}mutated.push(f.id);}else{if(page.children.some(n=>n.name==='Screen / '+key))throw Error('Screen exists '+key);f=stack(page,'Screen / '+key,402,0);}
 f.name='Screen / '+key;f.layoutMode='VERTICAL';f.resize(402,874);f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';f.itemSpacing=0;fill(f,'Canvas');f.clipsContent=true;f.x=160+(index%4)*474;f.y=1900+Math.floor(index/4)*1050;
 const labelNode=txt(page,String(index+1).padStart(2,'0')+' / '+label,402,'Heading');labelNode.x=f.x;labelNode.y=f.y-44;
 await inst(M.status,f,'Status bar');const nav=fixed(f,'Navigation',402,44);nav.layoutMode='HORIZONTAL';nav.paddingLeft=16;nav.paddingRight=16;nav.itemSpacing=8;nav.counterAxisAlignItems='CENTER';
 if(back)await icon(nav,back==='close'?'xmark':'chevron.backward','BACK');else fixed(nav,'Leading space',44,44);
 const nt=txt(nav,navTitle,200,'Button');nt.textAlignHorizontal='CENTER';nt.layoutSizingHorizontal='FILL';if(summary)await icon(nav,'sun.max','day');if(settings)await icon(nav,'gearshape','settings');else fixed(nav,'Trailing space',44,44);
 const body=stack(f,'Scrollable content',402,24);body.paddingLeft=24;body.paddingRight=24;body.paddingTop=16;body.paddingBottom=24;body.resize(402,1);body.layoutSizingVertical='FILL';body.clipsContent=true;body.overflowDirection='VERTICAL';
 let foot=null;if(footer){foot=fixed(f,'Primary action region',402,footer);foot.paddingLeft=24;foot.paddingRight=24;foot.primaryAxisAlignItems='CENTER';}
 if(guide)await guidance(f,guide);if(tab)await inst(M[tab==='Brain Dump'?'tabCapture':'tab'+tab],f,'Tabs');await inst(M.home,f,'Home indicator');
 const data={key,id:f.id,index,label,body:body.id,footer:foot?.id,tab};screens.push(data);return{f,body,foot,nav,data};
}
async function task(parent,title,schedule='Today',goal='No goal',{review=false,key='groceries'}={}){const i=await inst(M.task,parent,'Task / '+key);own(i,'Title',title);for(const[name,label]of [['Schedule',schedule],['Goal link',goal]]){const wrap=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name===name);const native=wrap.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#488:193'in n.componentProperties);native.setProperties({'Label#488:193':label});mutated.push(native.id);action(wrap,name==='Schedule'?'menuSchedule':'menuGoal','OVERLAY');}const more=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name==='More actions');action(more,review?'menuReview':'menuMore','OVERLAY');const completion=i.findOne(n=>n.name==='Complete task');if(review){const t=completion.findAllWithCriteria({types:['TEXT']})[0];t.characters=figma.util.getSfSymbolCharacter('minus.circle');mutated.push(t.id);action(completion,'review-remove','REVIEW_REMOVE');}else action(completion,'task-complete','TASK_COMPLETE');return i;}
async function goal(parent,title='Guitar',detail='No entries yet',glyph='music.note',to='goal'){const i=await inst(M.goal,parent,title);own(i,'Title',title);own(i,'Detail',detail);own(i,'Symbol',figma.util.getSfSymbolCharacter(glyph));if(to)action(i,to);return i;}
async function preview(parent,title,detail){const i=await inst(M.preview,parent,title);own(i,'Title',title);own(i,'Detail',detail);return i;}
async function aiLink(parent){const r=stack(parent,'Processing',354,8,'HORIZONTAL');r.counterAxisAlignItems='CENTER';const t=txt(r,'Basic processing',190,'Small','Secondary');t.layoutSizingHorizontal='FILL';return button(r,'Set up AI','ai','Plain',130);}
async function composer(parent,{empty=false,compact=false}={}){const box=stack(parent,compact?'Transcript':'Composer',354,12);pad(box,16);roundedCard(box);txt(box,compact?'YOUR RECORDING':'INPUT',322,'Caption','Secondary');const content=txt(box,empty?'Type what you need to do, or record it.':compact?'Buy groceries today. Call the dentist this week. I’d like to learn guitar…':'Buy groceries today. Call the dentist this week. I’d like to learn guitar.',322,'Body',empty?'Secondary':'Ink');if(!compact&&!empty){content.resize(322,76);content.textAutoResize='NONE';}if(compact)action(box,'typing');else{action(content,'typing');const row=stack(box,'Input actions',322,8,'HORIZONTAL');await icon(row,'mic.fill','voice');const space=fixed(row,'Spacer',1,44);space.layoutSizingHorizontal='FILL';await button(row,empty?'Type':'Done','capture','Plain',92);}return box;}
async function previewGroups(body){const head=stack(body,'Preview title',354,8,'HORIZONTAL');const title=txt(head,'Preview',180,'Heading');title.layoutSizingHorizontal='FILL';await count(head,'Task',2);await count(head,'Goal',1);const tasks=section(body,'Tasks');await preview(tasks,'Buy groceries','Today');await preview(tasks,'Call the dentist','This Week');const goals=section(body,'Goals');await goal(goals,'Guitar','New goal','music.note',null);}
function result(extra={}){return summary({screens,actions,...extra});}
