// Append ../common.js. Update linked masters in place; preserve card instance IDs.
figma.skipInvisibleInstanceChildren=false;C.Forest='#326B59';
const M={task:'1096:663',menu:'1096:611',icon:'1096:540',plain:'1096:559'};
const vars=await figma.variables.getLocalVariablesAsync();const state=Object.fromEntries(vars.filter(v=>v.variableCollectionId==='VariableCollectionId:1125:2545').map(v=>[v.name,v]));
// Owner-requested goal naming: prototype fixtures only.
for(const v of Object.values(state)){if(v.resolvedType==='STRING')for(const [mode,value]of Object.entries(v.valuesByMode)){if(value==='Read more'||value==='Run regularly')v.setValueForMode(mode,value==='Read more'?'Read':'Run');}}
function renameValue(v){if(v==='Read more')return'Read';if(v==='Run regularly')return'Run';if(Array.isArray(v))return v.map(renameValue);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,renameValue(x)]));return v;}
const all=page.findAll(()=>true);const fontMap=new Map();for(const t of all.filter(n=>n.type==='TEXT'))for(const s of t.getStyledTextSegments(['fontName']))fontMap.set(JSON.stringify(s.fontName),s.fontName);await Promise.all([...fontMap.values()].map(f=>figma.loadFontAsync(f)));
for(const n of all){if(n.type==='INSTANCE'){const props={};for(const[k,p]of Object.entries(n.componentProperties))if(p.type==='TEXT'&&['Read more','Run regularly'].includes(p.value))props[k]=renameValue(p.value);if(Object.keys(props).length){n.setProperties(props);mutated.push(n.id);}}if(n.type==='TEXT'&&['Read more','Run regularly'].includes(n.characters)){n.characters=renameValue(n.characters);mutated.push(n.id);}if('reactions'in n&&n.reactions.length&&/Read more|Run regularly/.test(JSON.stringify(n.reactions))){await n.setReactionsAsync(renameValue(n.reactions));mutated.push(n.id);}}
const board=stack(page,'Revision 3 · component refinements',1250,24);board.x=3720;board.y=160;board.paddingTop=24;board.paddingBottom=24;board.paddingLeft=24;board.paddingRight=24;fill(board,'Surface');board.cornerRadius=24;
txt(board,'Revision 3 · controls and capture',1202,'Title');txt(board,'Native navigation, quiet content controls. Edit the masters to update the screen examples.',1202,'Body','Secondary');
// A native borderless symbol button, replacing glass only where it is content UI.
const plain=(await figma.getNodeByIdAsync(M.plain)).clone();keep(plain);board.appendChild(plain);plain.name='AI1 / Plain icon action';await fonts(plain);plain.resize(44,44);plain.children[0].setProperties({'Label Style':'Icon only','Symbol#5473:145':figma.util.getSfSymbolCharacter('ellipsis')});plain.children[0].resize(44,44);mutated.push(plain.children[0].id);plain.description='Native Apple borderless icon button; 44pt target. Use inside content, not as an individual glass bubble.';
const taskMain=await figma.getNodeByIdAsync(M.task);await fonts(taskMain);
const more=taskMain.findOne(n=>n.name==='More actions');more.swapComponent(plain);more.resize(44,44);mutated.push(more.id);
const title=taskMain.findOne(n=>n.name==='Task title');title.itemSpacing=8;const metadata=taskMain.findOne(n=>n.name==='Task metadata');metadata.paddingLeft=52;metadata.itemSpacing=8;metadata.resize(322,44);mutated.push(title.id,metadata.id,taskMain.id);
// Purpose-specific pill variants keep the Apple Menu button inside a Defog capsule.
const pills=[];const names=['Today','This Week','Someday','No goal','Guitar','Read','Run'];
for(const name of names){const isSchedule=names.indexOf(name)<3;const main=comp('Pill',isSchedule?98:126,0);board.appendChild(main);main.name='Kind='+name;main.resize(isSchedule?98:126,44);main.primaryAxisSizingMode='FIXED';main.counterAxisSizingMode='FIXED';const bg=stack(main,'Pill surface',main.width,0);bg.resize(main.width,30);bg.layoutPositioning='ABSOLUTE';bg.x=0;bg.y=7;bg.cornerRadius=15;bg.primaryAxisSizingMode='FIXED';bg.counterAxisSizingMode='FIXED';fill(bg,name==='Today'?'Peach':name==='This Week'?'Lilac':name==='Someday'?'Canvas':name==='No goal'?'Surface':'Sage');if(name==='No goal'){bg.strokes=[{type:'SOLID',color:rgb(C.Secondary),opacity:.55}];bg.strokeWeight=1;bg.dashPattern=[3,3];}
const menu=await inst(M.menu,main,'Native menu');menu.resize(main.width,44);const native=menu.children[0];native.setProperties({'Label#488:193':name==='No goal'?'+ Link to goal':name});native.paddingLeft=10;native.paddingRight=8;native.resize(main.width,44);for(const t of native.findAllWithCriteria({types:['TEXT']})){t.fontSize=13;t.fontName={family:'SF Pro Rounded',style:'Medium'};t.lineHeight={unit:'PIXELS',value:18};fill(t,isSchedule?(name==='Today'?'Ink':name==='This Week'?'Plum':'Secondary'):name==='No goal'?'Secondary':'Forest');mutated.push(t.id);}main.description='Defog task metadata, 30pt visual pill within a 44pt native menu target. Text and color both identify status.';pills.push(main);}
const pillset=keep(figma.combineAsVariants(pills,board));pillset.name='AI1 / Task metadata pill';pillset.layoutMode='HORIZONTAL';pillset.itemSpacing=12;pillset.paddingLeft=8;pillset.paddingRight=8;pillset.paddingTop=8;pillset.paddingBottom=8;pillset.primaryAxisSizingMode='AUTO';pillset.counterAxisSizingMode='AUTO';
const pillByName=Object.fromEntries(pills.map(p=>[p.name.slice(5),p]));
// Preserve existing wrappers/reactions and bind variants to the same prototype state.
const cardInstances=page.children.filter(n=>n.name.startsWith('Screen /')).flatMap(f=>f.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name.startsWith('Task /')).map(i=>({i,f})));
for(const{name,label}of [{name:'Schedule',label:'Today'},{name:'Goal link',label:'No goal'}]){const p=taskMain.findOne(n=>n.type==='INSTANCE'&&n.name===name);p.swapComponent(pillByName[label]);p.resize(name==='Schedule'?98:126,44);mutated.push(p.id);}
for(const{i,f}of cardInstances){await fonts(i);const key=(f.name==='Screen / review'?'review-':'')+i.name.slice(7);for(const name of ['Schedule','Goal link']){const pill=i.findOne(n=>n.type==='INSTANCE'&&n.name===name);const variable=state['task/'+key+'/'+(name==='Schedule'?'schedule':'goal')];if(variable)pill.setProperties({Kind:{type:'VARIABLE_ALIAS',id:variable.id}});pill.resize(name==='Schedule'?98:126,44);mutated.push(pill.id);}const mi=i.findOne(n=>n.type==='INSTANCE'&&n.name==='More actions');mi.resize(44,44);mutated.push(mi.id);}
// Tight count badges, including instance size overrides.
for(const id of ['1116:1238','1116:1301']){const c=await figma.getNodeByIdAsync(id);await fonts(c);c.paddingLeft=10;c.paddingRight=10;c.itemSpacing=5;c.resize(58,36);const t=c.children.find(n=>n.type==='TEXT'&&/^\d/.test(n.characters));if(t){t.textAutoResize='WIDTH_AND_HEIGHT';t.layoutSizingHorizontal='HUG';mutated.push(t.id);}mutated.push(c.id);for(const i of page.findAllWithCriteria({types:['INSTANCE']})){const mc=await i.getMainComponentAsync();if(mc?.id===id){i.resize(58,36);mutated.push(i.id);}}}
// Separate trailing capture bubble, using the native Search Role geometry.
const tabs=[['1096:429','Home'],['1096:468','Tasks'],['1096:502','Goals'],['1116:1127','Brain Dump']];
for(const[id,selected]of tabs){const c=await figma.getNodeByIdAsync(id);await fonts(c);const native=c.children[0];native.setProperties({Type:'Search Role',Tabs:'4'});native.resize(402,95);await fonts(native);let k=0;for(const tab of native.findAllWithCriteria({types:['INSTANCE']})){if('Label#5735:10'in tab.componentProperties){const label=['Home','Tasks','Goals'][k];tab.setProperties({'Label#5735:10':label,'Symbol#5735:9':figma.util.getSfSymbolCharacter(['house','checklist','scope'][k]),Selected:selected===label?'True':'False'});k++;mutated.push(tab.id);}else if('Symbol#5735:8'in tab.componentProperties){tab.setProperties({'Symbol#5735:8':figma.util.getSfSymbolCharacter('waveform'),'Is Selected':selected==='Brain Dump'?'True':'False'});tab.name='Brain Dump shortcut';mutated.push(tab.id);}}tint(native);rounded(native,'Medium');mutated.push(c.id,native.id);}
// Native two-symbol group shares a single white glass background.
const group=await wrap(await figma.getNodeByIdAsync('1016:432'),'Home toolbar group',104,44);board.appendChild(group);let k=0;for(const n of group.findAllWithCriteria({types:['INSTANCE']})){if('Symbol#5429:0'in n.componentProperties){n.setProperties({'Symbol#5429:0':figma.util.getSfSymbolCharacter(['sun.max','gearshape'][k++])});mutated.push(n.id);}}
const nav=(await figma.getNodeByIdAsync('1097:589')).children.find(n=>n.name==='Navigation');for(const n of [...nav.children].filter(n=>['sun.max','gearshape'].includes(n.name))){removed.push(n.id);n.remove();}const groupI=await inst(group,nav,'Your Day and Settings');
const routes={Home:'1097:589',Tasks:'1097:823',Goals:'1097:919','Brain Dump':'1118:6207'};
const node=(id)=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:{type:'DISSOLVE',duration:.15,easing:{type:'EASE_OUT'}},resetScrollPosition:true});
const groupButtons=groupI.findAllWithCriteria({types:['INSTANCE']}).filter(n=>'Symbol#5429:0'in n.componentProperties);for(let j=0;j<groupButtons.length;j++){await groupButtons[j].setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[node(j?'1097:1082':'1119:2962')]}]);mutated.push(groupButtons[j].id);}
for(const f of page.children.filter(n=>n.name.startsWith('Screen /'))){const bar=f.children.find(n=>n.name==='Tabs');if(!bar)continue;await fonts(bar);for(const n of bar.findAllWithCriteria({types:['INSTANCE']})){const label=n.componentProperties['Label#5735:10']?.value;const dest=routes[label]||('Symbol#5735:8'in n.componentProperties?routes['Brain Dump']:null);if(dest&&dest!==f.id){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[node(dest)]}]);mutated.push(n.id);}}}
return summary({boardId:board.id,plainIcon:plain.id,pillSet:pillset.id,pills:Object.fromEntries(pills.map(p=>[p.name.slice(5),p.id])),toolbar:group.id,cards:cardInstances.length});
