// Append common.js. Fix visual issues identified from rendered screens.
figma.skipInvisibleInstanceChildren=false;C.Forest='#326B59';
function mark(n){mutated.push(n.id);return n;}
const nativeRow=(await figma.getNodeByIdAsync('1096:632')).children[0];const settingsGroup=await figma.getNodeByIdAsync('1119:2741');await fonts(settingsGroup);settingsGroup.primaryAxisSizingMode='AUTO';mark(settingsGroup);const settingsRow=await figma.getNodeByIdAsync('1119:2743');settingsRow.resize(354,52);settingsRow.children[0].resize(354,52);for(const p of ['paddingLeft','paddingRight','paddingTop','paddingBottom','primaryAxisAlignItems'])settingsRow.children[0][p]=nativeRow[p];mark(settingsRow);mark(settingsRow.children[0]);
// Home safe area is opaque below the tab slot; content still scrolls behind the floating tabs.
for(const f of page.children.filter(n=>n.name.startsWith('Screen /'))){const home=f.children.find(n=>n.name==='Home indicator');if(home){fill(home,'Canvas');mark(home);}const intro=f.findOne(n=>n.name==='Goal introduction');if(intro){await fonts(intro);for(const t of intro.children.filter(n=>n.type==='TEXT')){t.textAutoResize='HEIGHT';t.resize(354,t.height);mark(t);}const title=f.children.find(n=>n.name==='Navigation')?.children.find(n=>n.type==='TEXT');if(title){title.lineHeight={unit:'PIXELS',value:32};mark(title);}}}
const plain=await figma.getNodeByIdAsync('1161:3071');await fonts(plain);for(const t of plain.findAllWithCriteria({types:['TEXT']})){t.fontSize=22;t.lineHeight={unit:'PIXELS',value:28};mark(t);}
// Visible frame captions follow their moved screens.
for(const[id,frameId]of [['1165:2971','1165:2970'],['1165:3039','1165:3038']]){const label=await figma.getNodeByIdAsync(id);const f=await figma.getNodeByIdAsync(frameId);label.x=f.x;label.y=f.y-44;mark(label);}
// A short title-collapse specimen: native scrolling is documented separately.
const collapsed=[];
for(const[id,title,x]of [['1097:589','Home',3720],['1097:823','Tasks',4194],['1097:685','Brain Dump',4668]]){const original=await figma.getNodeByIdAsync(id);await fonts(original);const f=original.clone();keep(f);f.name='Screen / '+title.toLowerCase().replaceAll(' ','-')+'-collapsed';f.x=x;f.y=5050;const body=f.children.find(n=>n.name==='Scrollable content');body.paddingTop=12;const large=body.children.find(n=>n.name==='Heading');if(large){removed.push(large.id);large.remove();}const nav=f.children.find(n=>n.name==='Navigation');const t=nav.children.find(n=>n.type==='TEXT');t.characters=title;t.name='Collapsed title';t.textAlignHorizontal='CENTER';t.layoutPositioning='ABSOLUTE';t.resize(170,22);t.x=116;t.y=11;mark(t);const label=txt(page,title+' · collapsed title specimen',402,'Heading');label.x=x;label.y=f.y-44;
const transition={type:'SMART_ANIMATE',duration:.28,easing:{type:'EASE_OUT'}};const heading=original.findOne(n=>n.name==='Heading');await heading.setReactionsAsync([{trigger:{type:'ON_DRAG'},actions:[{type:'NODE',destinationId:f.id,navigation:'NAVIGATE',transition,resetScrollPosition:true}]}]);mark(heading);await nav.setReactionsAsync([{trigger:{type:'ON_DRAG'},actions:[{type:'NODE',destinationId:original.id,navigation:'NAVIGATE',transition,resetScrollPosition:true}]}]);mark(nav);collapsed.push({id:f.id,title,source:id});}
// Main screen navigation returns to the stored draft specimen after input/preview.
const prototypeVars=await figma.variables.getLocalVariablesAsync();const collection=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:1125:2545');let hasDraft=prototypeVars.find(v=>v.variableCollectionId===collection.id&&v.name==='hasDraft');if(!hasDraft){hasDraft=figma.variables.createVariable('hasDraft',collection,'BOOLEAN');hasDraft.scopes=['ALL_SCOPES'];hasDraft.setValueForMode(collection.defaultModeId,false);}
const nav=id=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:true});
const setDraft=value=>({type:'SET_VARIABLE',variableId:hasDraft.id,variableValue:{type:'BOOLEAN',resolvedType:'BOOLEAN',value}});
for(const f of page.children.filter(n=>n.name.startsWith('Screen /'))){const bar=f.children.find(n=>n.name==='Tabs');if(!bar)continue;const captured=['Screen / capture','Screen / capture-ai','Screen / transcript','Screen / capture-ready'].includes(f.name);for(const i of bar.findAllWithCriteria({types:['INSTANCE']})){if('Symbol#5735:8'in i.componentProperties){const cond={type:'CONDITIONAL',conditionalBlocks:[{condition:{type:'VARIABLE_ALIAS',resolvedType:'BOOLEAN',value:{type:'VARIABLE_ALIAS',id:hasDraft.id}},actions:[nav('1165:2970')]},{actions:[nav('1118:6207')]}]};await i.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[cond]}]);mark(i);}else if(captured&&i.reactions.length){await i.setReactionsAsync(i.reactions.map(r=>({...r,actions:[setDraft(true),...r.actions]})));mark(i);}}}
// Processing cancellation retains the fixed draft. Saving ends this draft specimen.
const save=await figma.getNodeByIdAsync('1119:2130');await save.setReactionsAsync(save.reactions.map(r=>({...r,actions:[setDraft(false),...r.actions]})));mark(save);
const notes=await figma.getNodeByIdAsync('1131:2634');await fonts(notes);for(const child of [...notes.children]){removed.push(child.id);child.remove();}notes.name='Revision 3 · review notes';txt(notes,'Revision 3 · quieter controls and capture',1352,'Title');txt(notes,'Try the separate waveform button, type or record → Process → Preview → Review → Save, task menus, and Home’s grouped toolbar. Drag a large page heading upward to view the collapsed-title specimen; drag the small navigation title to return.',1352,'Body');txt(notes,'Figma uses fixed example text and a timed processing transition. Voice input and AI calls are not running. Actual scroll-driven title collapse is an iOS implementation requirement; this prototype demonstrates its two visual states. Read / Run are proposed generated goal names, not changes to saved app data.',1352,'Small','Secondary');mark(notes);
page.flowStartingPoints=[...page.flowStartingPoints.filter(f=>!f.name.includes('processing')),{nodeId:'1118:6207',name:'06 · Revised capture flow'},{nodeId:'1165:2970',name:'07 · Input ready to process'}];mark(page);
return summary({collapsed,hasDraft:hasDraft.id});
