// Append common.js, revision-2 masters M, then revision-2/screen-helpers.js.
figma.skipInvisibleInstanceChildren=false;
const node=(id,transition=null)=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition,resetScrollPosition:true});
async function link(n,id,transition=null){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[node(id,transition)]}]);mutated.push(n.id);}
function del(n){if(n){removed.push(n.id);n.remove();}}
function absolute(n,x,y,w=n.width,h=n.height){n.layoutPositioning='ABSOLUTE';n.resize(w,h);n.x=x;n.y=y;mutated.push(n.id);}
const board=await figma.getNodeByIdAsync('1161:3068');
const cancel=(await figma.getNodeByIdAsync(M.buttonPlain)).clone();keep(cancel);board.appendChild(cancel);cancel.name='AI1 / Cancel input';await fonts(cancel);cancel.resize(142,52);fill(cancel,'Peach');cancel.cornerRadius=26;nativeText(cancel,'Cancel');for(const t of cancel.findAllWithCriteria({types:['TEXT']})){fill(t,'Ink');mutated.push(t.id);}cancel.description='Muted cancellation button. Cancels the in-progress operation; does not save tasks.';
// Make content-level overflow and guidance dismissal quiet, retaining native buttons.
for(const c of [await figma.getNodeByIdAsync('1161:3071')]){await fonts(c);for(const t of c.findAllWithCriteria({types:['TEXT']})){fill(t,'Secondary');mutated.push(t.id);}}
for(const id of [M.guidanceTask,M.guidanceGoal,M.guidanceInput,M.guidanceSaved]){const c=await figma.getNodeByIdAsync(id);await fonts(c);const dismiss=c.findOne(n=>n.type==='INSTANCE'&&n.name==='Dismiss guidance');dismiss.swapComponent(await figma.getNodeByIdAsync('1161:3071'));dismiss.resize(44,44);dismiss.children[0].setProperties({'Symbol#5473:145':figma.util.getSfSymbolCharacter('xmark')});mutated.push(dismiss.id);}
// Single goal title; the small native symbol in the nav retains green identity.
for(const f of page.children.filter(n=>n.name.startsWith('Screen /'))){const intro=f.findOne(n=>n.name==='Goal introduction');if(!intro)continue;await fonts(f);const glyph=intro.children.find(n=>n.type==='TEXT'&&n.name.startsWith('SF Symbol'));const navTitle=f.children.find(n=>n.name==='Navigation')?.children.find(n=>n.type==='TEXT');if(navTitle&&glyph){navTitle.fontName={family:'SF Pro',style:'Regular'};navTitle.fontSize=26;navTitle.characters=glyph.characters;fill(navTitle,'Forest');mutated.push(navTitle.id);del(glyph);}intro.fills=[];intro.paddingLeft=0;intro.paddingRight=0;intro.paddingTop=0;intro.paddingBottom=0;intro.itemSpacing=6;for(const t of intro.children.filter(n=>n.type==='TEXT')){t.resize(354,t.height);mutated.push(t.id);}mutated.push(intro.id);}
// Shared floating input component, native controls with a plain card surface.
const composerVariants=[];
for(const mode of ['Empty','Filled','Transcript','Processing']){const c=comp('Capture composer',354,12);board.appendChild(c);c.name='State='+mode;pad(c,16);roundedCard(c,'Surface',24);const content=txt(c,mode==='Empty'?'Buy groceries today, call the dentist…':mode==='Processing'?'Finding tasks and goals…':mode==='Transcript'?'Buy groceries today. Call the dentist this week. I’d like to learn guitar…':'Buy groceries today. Call the dentist this week. I’d like to learn guitar.',322,'Body',mode==='Empty'||mode==='Processing'?'Secondary':'Ink');content.name='Input text';if(mode==='Empty')content.resize(322,66);if(mode==='Empty')content.textAutoResize='NONE';
const row=stack(c,'Composer actions',322,12,'HORIZONTAL');row.counterAxisAlignItems='CENTER';
if(mode==='Processing'){const spinner=symbol(row,'arrow.trianglehead.2.clockwise.rotate.90',22);const spacer=fixed(row,'Spacer',1,44);spacer.layoutSizingHorizontal='FILL';const cancelI=await inst(cancel,row,'Cancel processing');cancelI.resize(142,44);}else{const mic=await inst('1161:3071',row,'Record voice');mic.children[0].setProperties({'Symbol#5473:145':figma.util.getSfSymbolCharacter('mic.fill')});const spacer=fixed(row,'Spacer',1,44);spacer.layoutSizingHorizontal='FILL';if(mode!=='Empty'){const b=await button(row,'Process',null,'Primary',242);b.resize(242,44);}}
c.description='Floating input surface. Process appears after input; processing preserves the transcript and offers cancellation. Figma uses fixed example text.';composerVariants.push(c);}
const composerSet=keep(figma.combineAsVariants(composerVariants,board));composerSet.name='AI1 / Capture composer';composerSet.layoutMode='VERTICAL';composerSet.itemSpacing=16;composerSet.paddingLeft=8;composerSet.paddingRight=8;composerSet.paddingTop=8;composerSet.paddingBottom=8;composerSet.primaryAxisSizingMode='AUTO';composerSet.counterAxisSizingMode='AUTO';const composerByName=Object.fromEntries(composerVariants.map(c=>[c.name.slice(6),c]));
// New input and processing specimens keep existing entry/preview screen IDs stable.
const ready=await screen('capture-ready','Brain Dump · ready to process',28,{tab:'Brain Dump',settings:true,footer:196});ready.f.x=3720;ready.f.y=4000;await heading(ready.body,'Brain Dump');await aiLink(ready.body);txt(ready.body,'Add a date or link a task to a goal during review.',354,'Small','Secondary');
const processing=await screen('processing','Brain Dump · processing',29,{tab:'Brain Dump',settings:true,footer:176});processing.f.x=4194;processing.f.y=4000;await heading(processing.body,'Brain Dump');await aiLink(processing.body);txt(processing.body,'Your input',354,'Heading');txt(processing.body,'Buy groceries today. Call the dentist this week. I’d like to learn guitar.',354,'Body','Secondary');
async function addComposer(f,foot,mode){const c=await inst(composerByName[mode],foot,'Floating composer');for(const n of c.findAllWithCriteria({types:['INSTANCE']})){if(n.name==='Record voice')await link(n,'1118:6581');if(n.name==='Process')await link(n,processing.f.id,{type:'SMART_ANIMATE',duration:.3,easing:{type:'EASE_OUT'}});if(n.name==='Cancel processing')await link(n,ready.f.id);}const input=c.findOne(n=>n.name==='Input text');if(mode!=='Processing')await link(input,'1118:6408');return c;}
await addComposer(ready.f,ready.foot,'Filled');await addComposer(processing.f,processing.foot,'Processing');
await processing.f.setReactionsAsync([{trigger:{type:'AFTER_TIMEOUT',timeout:1.6},actions:[node('1097:685',{type:'SMART_ANIMATE',duration:.3,easing:{type:'EASE_OUT'}})]}]);mutated.push(processing.f.id);
const empty=await figma.getNodeByIdAsync('1118:6207');await fonts(empty);const emptyBody=empty.children.find(n=>n.name==='Scrollable content');del(emptyBody.children.find(n=>n.name==='Composer'));for(const t of [...emptyBody.children].filter(n=>n.type==='TEXT'))del(t);txt(emptyBody,'Type or record what you need to do.\nYou can review it before saving.',354,'Body','Secondary');del(empty.children.find(n=>n.name==='Guidance region'));const foot=fixed(empty,'Primary action region',402,196);foot.paddingLeft=24;foot.paddingRight=24;foot.primaryAxisAlignItems='CENTER';empty.insertChild(empty.children.indexOf(empty.children.find(n=>n.name==='Tabs')),foot);await addComposer(empty,foot,'Empty');
// Preview screens keep a compact editable transcript, not a second composer.
for(const id of ['1097:685','1119:3096','1118:6620']){const f=await figma.getNodeByIdAsync(id);await fonts(f);const body=f.children.find(n=>n.name==='Scrollable content');const old=body.children.find(n=>['Composer','Transcript'].includes(n.name));if(old){const at=body.children.indexOf(old);del(old);const summary=stack(body,'Input summary · tap to edit',354,6);pad(summary,12);roundedCard(summary,'Surface',16);txt(summary,'Buy groceries today. Call the dentist this week. I’d like to learn guitar…',330,'Small','Secondary');body.insertChild(at,summary);await link(summary,'1118:6408');}body.itemSpacing=16;mutated.push(body.id);}
// Keyboard input: Process replaces Done and keeps native keyboard.
const typing=await figma.getNodeByIdAsync('1118:6408');await fonts(typing);const actionButton=typing.children.find(n=>n.name==='Primary action region').children[0];actionButton.swapComponent(await figma.getNodeByIdAsync(M.buttonPrimary));actionButton.name='Process';nativeText(actionButton,'Process');await link(actionButton,processing.f.id,{type:'SMART_ANIMATE',duration:.3,easing:{type:'EASE_OUT'}});
// Voice: waveform + live subtitle; no decorative gradient or Recording label.
const voice=await figma.getNodeByIdAsync('1118:6581');await fonts(voice);const wave=voice.findOne(n=>n.name==='Voice gradient');wave.name='Voice waveform';wave.fills=[];wave.resize(354,180);for(const n of [...wave.children].filter(n=>n.type==='TEXT'))del(n);const voiceFoot=voice.children.find(n=>n.name==='Primary action region');voiceFoot.layoutMode='HORIZONTAL';voiceFoot.itemSpacing=12;voiceFoot.paddingRight=24;voiceFoot.resize(402,92);voiceFoot.counterAxisAlignItems='CENTER';const done=voiceFoot.children.find(n=>n.name==='Done');const vc=voiceFoot.children.find(n=>n.name==='Cancel');vc.swapComponent(cancel);vc.resize(142,52);nativeText(vc,'Cancel');done.name='Process';done.resize(200,52);nativeText(done,'Process');voiceFoot.insertChild(0,vc);await link(vc,'1118:6207');await link(done,processing.f.id,{type:'SMART_ANIMATE',duration:.3,easing:{type:'EASE_OUT'}});mutated.push(wave.id,voiceFoot.id,done.id,vc.id);
// Keep AI configuration aligned to the content's trailing edge.
for(const f of page.children.filter(n=>n.name.startsWith('Screen /'))){await fonts(f);for(const row of f.findAll(n=>n.type==='FRAME'&&n.name==='Processing')){row.resize(354,44);const b=row.children.find(n=>n.type==='INSTANCE');if(b){b.resize(110,44);const native=b.children[0];native.resize(110,44);native.paddingLeft=0;native.paddingRight=0;native.primaryAxisAlignItems='MAX';mutated.push(b.id,native.id);}mutated.push(row.id);}}
// Scroll behind the bars. Keep chrome in fixed slots and replace the hard cut at y106.
const treated=[];
for(const f of page.children.filter(n=>n.name.startsWith('Screen /')&&!['Screen / onboarding','Screen / onboarding-2','Screen / storage','Screen / voice'].includes(n.name))){await fonts(f);const body=f.children.find(n=>n.name==='Scrollable content');if(!body)continue;const positions=f.children.map(n=>({n,x:n.x,y:n.y,w:n.width,h:n.height}));const oldY=body.y;const oldBottom=body.y+body.height;for(const {n,x,y,w,h}of positions)absolute(n,x,y,w,h);body.paddingTop+=oldY;body.paddingBottom+=Math.max(874-oldBottom,34);body.primaryAxisAlignItems='MIN';absolute(body,0,0,402,874);f.insertChild(0,body);const edge=fade(f,'Top scroll edge · soft',402,116,'Canvas','Canvas',1,0);edge.fills=[{type:'GRADIENT_LINEAR',gradientTransform:[[0,1,0],[-1,0,1]],gradientStops:[{position:0,color:{...rgb(C.Canvas),a:1}},{position:.52,color:{...rgb(C.Canvas),a:1}},{position:.75,color:{...rgb(C.Canvas),a:.88}},{position:1,color:{...rgb(C.Canvas),a:0}}]}];absolute(edge,0,0,402,116);f.insertChild(1,edge);
const guidanceRegion=f.children.find(n=>n.name==='Guidance region');const footer=f.children.find(n=>n.name==='Primary action region');const tab=f.children.find(n=>n.name==='Tabs');const start=guidanceRegion?.y??footer?.y??tab?.y??840;const end=tab?840:f.children.find(n=>n.name==='Apple keyboard')?.y??840;
if(end>start){if(guidanceRegion){const existing=guidanceRegion.children.find(n=>n.name==='White fade');if(existing)del(existing);guidanceRegion.clipsContent=false;mutated.push(guidanceRegion.id);}const bg=fade(f,'Bottom scroll edge',402,end-start+24,'Canvas','Canvas',0,1);absolute(bg,0,start-24,402,end-start+24);f.insertChild(2,bg);}treated.push(f.id);}
// Wire new screens' tabs and top actions.
for(const s of [ready,processing]){for(const a of actions.filter(a=>s.f.findOne(n=>n.id===a.id))){const n=await figma.getNodeByIdAsync(a.id);if(a.to==='ai')await link(n,'1119:2899');if(a.to==='settings')await link(n,'1097:1082');}const bar=s.f.children.find(n=>n.name==='Tabs');for(const n of bar.findAllWithCriteria({types:['INSTANCE']})){const label=n.componentProperties['Label#5735:10']?.value;const id={Home:'1097:589',Tasks:'1097:823',Goals:'1097:919'}[label]||('Symbol#5735:8'in n.componentProperties?'1118:6207':null);if(id)await link(n,id);}}
return summary({ready:ready.f.id,processing:processing.f.id,composerSet:composerSet.id,composerVariants:Object.fromEntries(composerVariants.map(c=>[c.name.slice(6),c.id])),cancel:cancel.id,scrollTreated:treated});
