// Append after common.js. Current-app structures, component candidates only.
async function copyComponent(id,name){const src=await figma.getNodeByIdAsync(id);if(!src)throw Error('Source missing '+id);await fonts(src);const copy=src.clone();page.appendChild(copy);const c=figma.createComponentFromNode(copy);created.push(c.id,...c.findAll(()=>true).map(n=>n.id));c.name=name;c.reactions=[];return c;}
async function inst(id,parent,name){const c=await figma.getNodeByIdAsync(id);await fonts(c);const i=track(c.createInstance());parent.appendChild(i);i.name=name||c.name;return i;}
function comp(name,w,gap=8,direction='VERTICAL'){const c=track(figma.createComponent());c.name=name;c.layoutMode=direction;c.resize(w,1);c.primaryAxisSizingMode=direction==='VERTICAL'?'AUTO':'FIXED';c.counterAxisSizingMode=direction==='VERTICAL'?'FIXED':'AUTO';c.fills=[];c.itemSpacing=gap;return c;}
function prop(c,match,label){const t=c.findAllWithCriteria({types:['TEXT']}).find(n=>match(n));if(t)exposeText(c,t,label);return t;}
function swapNode(old,i){const p=old.parent;const idx=p.children.indexOf(old);p.insertChild(idx,i);removed.push(old.id);old.remove();}
function nativeLabel(i,label){const n=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#488:0'in n.componentProperties);if(n){n.setProperties({'Label#488:0':label});mutated.push(n.id);}return i;}
const pills=[];for(const[variantName,value]of [['Today','Today'],['This Week','This Week'],['Someday','Someday']]){const c=comp('Schedule='+variantName,100);const i=await inst('1055:908',c);i.resize(100,44);i.isExposedInstance=true;const native=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#488:193'in n.componentProperties);native.setProperties({'Label#488:193':value});mutated.push(native.id);pills.push(c);}await family(1,'Schedule control','Native menu trigger adapted to Today / This Week / Someday. Current TaskSchedule meanings retained.',pills);
const link=[];for(const state of ['Unlinked','Linked']){const c=await copyComponent('984:161','State='+state);c.resize(122,44);c.primaryAxisAlignItems='CENTER';c.counterAxisAlignItems='CENTER';const t=prop(c,()=>true,'Label');t.characters=state==='Linked'?'Guitar':'+ Link to goal';t.fontName={family:'SF Pro Rounded',style:'Medium'};t.resize(114,16);t.textAlignHorizontal='CENTER';if(state==='Linked'){c.dashPattern=[];c.strokes=[paint('blue')];t.fills=[paint('blue')];}link.push(c);}const links=await family(1,'Goal link pill','Unlinked / Linked. Defog TaskPillView composition; full 44pt target even when the visible pill is smaller.',link);
const taskVariants=[];for(const state of ['Active','Completed','Preview']){const c=await copyComponent(state==='Preview'?'984:353':'984:153','State='+state);c.itemSpacing=8;c.layoutSizingVertical='HUG';c.fills=[paint('surface')];const title=prop(c,n=>n.characters==='Buy groceries today','Title');if(title){title.textStyleId=styles.Body.id;title.textDecoration=state==='Completed'?'STRIKETHROUGH':'NONE';if(state==='Completed')title.fills=[paint('secondary')];}
const metadata=c.findOne(n=>n.type==='FRAME'&&n.name==='Task metadata');
if(metadata){if(state==='Completed')metadata.visible=false;else{metadata.resize(346,44);metadata.layoutSizingVertical='HUG';const oldSchedule=metadata.children.find(n=>n.name.includes('Today'));if(oldSchedule){const s=await inst(pills[0].id,metadata,'Schedule');swapNode(oldSchedule,s);s.isExposedInstance=true;}const oldLink=metadata.children.find(n=>n.name==='Link to goal');if(oldLink){const s=await inst(link[0].id,metadata,'Goal link');swapNode(oldLink,s);s.isExposedInstance=true;}}}
if(state==='Completed'){const check=c.findAllWithCriteria({types:['TEXT']}).find(n=>n.characters===figma.util.getSfSymbolCharacter('circle'));if(check){check.characters=figma.util.getSfSymbolCharacter('checkmark.circle.fill');check.fills=[paint('blue')];}}
taskVariants.push(c);}await family(1,'Task card','Active / Completed / Live preview. Title is a component property; schedule and goal controls are linked subcomponents. Source: TaskCardView + TaskCardChrome.',taskVariants);
const section=comp('Default',370);const st=text(section,'Active Goals',370,'Title');exposeText(section,st,'Title');await family(0,'Section heading','SF Pro Rounded Bold · 22/28. Edit this master to update headings in context screens.',[section]);
const compact=await copyComponent('984:145','Size=Compact');compact.fills=[paint('surface')];prop(compact,n=>n.characters==='Guitar','Title');prop(compact,n=>n.characters==='Updated today','Detail');rounded(compact);
const full=comp('Size=List',370,12,'HORIZONTAL');full.paddingLeft=16;full.paddingRight=16;full.paddingTop=16;full.paddingBottom=16;full.cornerRadius=12;full.fills=[paint('surface')];full.counterAxisAlignItems='CENTER';const dot=track(figma.createEllipse());full.appendChild(dot);dot.name='Goal color';dot.resize(12,12);dot.fills=[{type:'SOLID',color:{r:.655,g:.545,b:.98}}];const labels=stack(full,'Goal content',286,4);const gt=text(labels,'Guitar',286,'Headline');const gd=text(labels,'1 entry',286,'Caption','secondary');exposeText(full,gt,'Title');exposeText(full,gd,'Detail');const chevron=text(full,figma.util.getSfSymbolCharacter('chevron.right'),16,'Body','secondary');chevron.fontName={family:'SF Pro',style:'Regular'};
await family(2,'Goal card','Compact Home carousel / Goals list. SF Pro Rounded heading, entry-count detail. Source: GoalCardView; sample goal color remains editable.',[compact,full]);
const entries=[];for(const type of ['Quick','Note']){const c=await copyComponent('984:482','Type='+type);prop(c,n=>n.characters.includes('Sep'),'Date');const value=prop(c,n=>n.characters.includes('Did something'),'Entry');if(type==='Note'){value.fontName={family:'SF Pro',style:'Regular'};value.characters='Practised chord changes for 10 minutes.';value.textAutoResize='HEIGHT';value.resize(310,value.height);c.layoutSizingVertical='HUG';const inner=value.parent;inner.layoutSizingVertical='HUG';}entries.push(c);}await family(2,'Timeline entry','Quick / Detailed note. Factual date and entry text; the current-app quick entry remains italic. Source: TimelineTabView.',entries);
const dayVariants=[];for(const state of ['Empty','Logged','Today']){const c=comp('State='+state,44);c.resize(44,44);c.primaryAxisSizingMode='FIXED';c.counterAxisAlignItems='CENTER';c.primaryAxisAlignItems='CENTER';c.cornerRadius=6;c.fills=[state==='Logged'?paint('blue'):paint('surface')];if(state==='Today'){c.strokes=[paint('label')];c.strokeWeight=2;}const t=text(c,'28',28,'Caption');t.textAlignHorizontal='CENTER';if(state==='Logged')t.fills=[{type:'SOLID',color:{r:1,g:1,b:1}}];exposeText(c,t,'Day');dayVariants.push(c);}await family(2,'Calendar day','Empty / Logged / Today. Defog’s 35-day progress grid, not a date-input picker. Date label is editable.',dayVariants);
const progress=comp('Default',370,8,'HORIZONTAL');progress.counterAxisAlignItems='CENTER';const quick=await inst('1055:583',progress,'Quick progress');quick.resize(314,48);nativeLabel(quick,'Did something today');quick.isExposedInstance=true;const add=await inst('1055:552',progress,'Add note');add.resize(48,48);const glyph=add.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#5429:13'in n.componentProperties);glyph.setProperties({'Label#5429:13':figma.util.getSfSymbolCharacter('square.and.pencil')});mutated.push(glyph.id);add.isExposedInstance=true;await family(2,'Progress actions','Quick entry + Add note. Native controls, SF Pro Rounded label; test the candidate styling in Goal detail.',[progress]);
const liveGoal=await copyComponent('984:367','Default');prop(liveGoal,n=>n.characters==='Guitar','Title');rounded(liveGoal);await family(3,'Goal preview row','Defog live extraction preview. The content is a component text property.',[liveGoal]);
const composer=[];for(const state of ['Empty','Filled']){const c=await copyComponent('984:371','State='+state);const edit=c.findOne(n=>n.type==='FRAME'&&n.name==='Text editor');const input=prop(c,n=>n.characters.includes('Buy groceries'),'Input');input.characters=state==='Filled'?'Buy groceries today\nCall the dentist this week\nLearn guitar':'What’s on your mind?';input.fills=[paint(state==='Filled'?'label':'secondary')];const actions=c.findOne(n=>n.type==='FRAME'&&n.name==='Capture actions');const old=actions.children.find(n=>n.name==='Process');const process=await inst(state==='Filled'?'1055:583':'1055:592',actions,'Process');process.resize(302,56);nativeLabel(process,'Process');swapNode(old,process);process.isExposedInstance=true;const micOld=actions.children.find(n=>n.name==='Microphone');const mic=await inst('1055:552',actions,'Microphone');mic.resize(56,56);const glyph=mic.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#5429:13'in n.componentProperties);glyph.setProperties({'Label#5429:13':figma.util.getSfSymbolCharacter('mic.fill')});mutated.push(glyph.id);swapNode(micOld,mic);mic.isExposedInstance=true;composer.push(c);}await family(3,'Capture composer','Empty / Filled. Current TextEditor composition and permission message, with native action instances. Source: BrainDumpView. Copy remains baseline, not a redesigned flow.',composer);
const labeled=comp('Default',370,8);const fl=text(labeled,'Model ID',370,'Headline');exposeText(labeled,fl,'Label');const fi=await inst('1055:675',labeled,'Value');fi.isExposedInstance=true;const help=text(labeled,'Use the exact model name from your provider.',370,'Caption','secondary');exposeText(labeled,help,'Helper');await family(4,'Labeled field','Candidate composition: persistent label + native field + helper. Tests audit UX-08; not implemented.',[labeled]);
const toast=comp('Default',300,0);toast.paddingLeft=16;toast.paddingRight=16;toast.paddingTop=10;toast.paddingBottom=10;toast.cornerRadius=100;toast.fills=[{type:'SOLID',color:{r:0,g:0,b:0},opacity:.8}];const msg=text(toast,'Task moved to This Week',268,'Callout');msg.fills=[{type:'SOLID',color:{r:1,g:1,b:1}}];msg.textAlignHorizontal='CENTER';exposeText(toast,msg,'Message');await family(5,'Toast','Current app feedback surface. Message property; duration and bottom placement are runtime behavior. Source: ToastModifier.',[toast]);
const empty=comp('Default',370,12);empty.counterAxisAlignItems='CENTER';const ei=text(empty,figma.util.getSfSymbolCharacter('target'),338,'Title','secondary');ei.fontName={family:'SF Pro',style:'Regular'};ei.textAlignHorizontal='CENTER';const et=text(empty,'No goals yet',338,'Title');et.textAlignHorizontal='CENTER';exposeText(empty,et,'Title');const ed=text(empty,'Add one with a brain dump.',338,'Body','secondary');ed.textAlignHorizontal='CENTER';exposeText(empty,ed,'Message');await family(5,'Empty state','Defog empty-state composition. Title/message editable; icon is an SF Symbol, not an illustration.',[empty]);
const daily=comp('Default',354,24);daily.paddingLeft=24;daily.paddingRight=24;daily.paddingTop=24;daily.paddingBottom=24;daily.cornerRadius=24;daily.fills=[paint('surface')];const title=text(daily,'Move yesterday’s Today tasks?',306,'Title');title.textAlignHorizontal='CENTER';const message=text(daily,'You have 3 tasks left over from yesterday. Would you like to move them to This Week?',306,'Callout','secondary');message.textAlignHorizontal='CENTER';exposeText(daily,message,'Message');for(const[id,label]of [['1055:583','Move to This Week'],['1055:586','Keep in Today'],['1055:595','Not now']]){const b=await inst(id,daily,label);b.resize(306,50);nativeLabel(b,label);b.isExposedInstance=true;}await family(5,'Daily prompt','Current-app decision and copy, composed from native button instances. Source: DailyPromptOverlay. Dismiss behavior still needs runtime validation.',[daily]);
return summary();
