// Append after common.js. No changes to baseline or paused redesign pages.
const status=await figma.importComponentByKeyAsync('e01a1714aeec1a5a0a6453485bf16e975008b282');await fonts(status);
await family(0,'Status bar','Apple iOS27 · full 402 × 62 region. Device typography stays native.',[wrapper(status,'Default',402,62,{'Time#5466:4':'9:41'},false)]);
await family(0,'Home indicator','Apple iOS27 · full 402 × 34 region; reserve the whole region.',[wrapper(await native('db1fd2b84f66cfc75ab693b5b0b77b90ae471e38','Device=iPhone, Orientation=Portrait'),'Default',402,34,{},false)]);
const tabs=[];for(const selected of ['Home','Tasks','Goals']){const c=wrapper(await native('971f4862d60ea7fb60429ff57f4e51dc42758f6a','Minimized=False, Tabs=4, Type=Search Role'),'Selected='+selected,402,95,{},false);const i=c.children[0];const dest=i.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name==='Tab');dest.forEach((n,j)=>{n.setProperties({'Label#5735:10':['Home','Tasks','Goals'][j],'Symbol#5735:9':figma.util.getSfSymbolCharacter(['house.fill','checkmark.square.fill','target'][j]),Selected:selected===['Home','Tasks','Goals'][j]?'True':'False'});mutated.push(n.id);});const add=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name==='Search Tab');add.setProperties({'Symbol#5735:8':figma.util.getSfSymbolCharacter('plus')});mutated.push(add.id);rounded(i);i.resize(402,95);i.layoutSizingVertical='FIXED';i.minHeight=95;tabs.push(c);}await family(0,'Tab bar','Current app destinations and Add action retained for context. Audit UX-03 remains open. Full bounds: 95pt.',tabs);
const nav=[];for(const[name,symbol]of [['Back','chevron.backward'],['More','ellipsis'],['Settings','gearshape'],['Summary','sun.max']]){const c=wrapper(await native('36df7438d67ed37c94488fd11d425899f1a902ba','Style=Glass, Is Enabled=True, Destructive=False'),'Action='+name,44,44);const label=c.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#5429:13'in n.componentProperties);label.setProperties({'Label#5429:13':figma.util.getSfSymbolCharacter(symbol)});mutated.push(label.id);nav.push(c);}await family(0,'Navigation action','Native Apple glass symbols. Label actions explicitly for VoiceOver in implementation.',nav);
const btn=[];for(const[role,nativeStyle,enabled,destructive,label]of [['Primary','Bordered - Prominent','True','False','Process'],['Secondary','Bordered','True','False','Keep in Today'],['Destructive','Bordered','True','True','Delete'],['Disabled','Bordered - Prominent','False','False','Test BYOM'],['Plain','Borderless','True','False','Next']]){btn.push(wrapper(await native('bba76d7e88d66c8704a07953ccc6056a185022b0',`Size=Large, Style=${nativeStyle}, Label Style=Title only, Is Enabled=${enabled}, Destructive=${destructive}`),'Role='+role,370,50,{'Label#488:0':label}));}await family(3,'Action button','Primary / Secondary / Destructive / Disabled / Plain. SF Pro Rounded labels; native states.',btn);
const seg=[];for(const selected of ['Timeline','Calendar']){const c=wrapper(await native('f508912e2177f4744038dc6591e976abf1040806','Size=Small, Is Enabled=True'),'Selected='+selected,370,32);const slot=c.findAllWithCriteria({types:['SLOT']}).find(n=>n.name==='Segments');for(const n of [...slot.children].slice(2)){removed.push(n.id);n.remove();}slot.children.forEach((n,j)=>{n.setProperties({'Title#10512:0':j?'Calendar':'Timeline','Is Selected':selected===(j?'Calendar':'Timeline')?'True':'False'});mutated.push(n.id);});rounded(c);seg.push(c);}await family(2,'Segmented control','Native Timeline / Calendar. Keep the full control below navigation; small 32pt visual.',seg);
const fields=[];for(const state of ['Placeholder','Focused','Value Entered']){fields.push(wrapper(await native('38117a30dd18e50d4c086b01121258a32567f920','State='+state),'State='+state,370,52,{'Value#519:17':state==='Placeholder'?'API key':'openai/gpt-4o-mini'},false));}await family(4,'Text field','Native Placeholder / Focused / Value Entered. Persistent label is a separate composition below.',fields);
const toggles=[];for(const[on,enabled]of [['False','True'],['True','True'],['False','False']]){const c=wrapper(await native('62c79e1affadacf2e24597674ca46f1806d32ffc',`State=Idle, Is On=${on}, Is Enabled=${enabled}`),`On=${on}, Enabled=${enabled}`,64,28,{'Show AX Label#6152:0':false},false);toggles.push(c);}await family(4,'Switch','Off / On / Disabled. Native switch visual is 64 × 28; place in a ≥44pt tappable row.',toggles);
const rows=[];for(const [height,subtitle]of [['Regular',false],['Tall',true]]){const c=wrapper(await native('da6c778eb113a68c7fd6f3828741ab33c3ec8f12','Height='+height),'Height='+height,370,height==='Regular'?52:68,{'Title#519:116':'Row title','Subtitle#519:149':'Supporting information','Show Subtitle#525:450':subtitle});rows.push(c);}await family(4,'List row','Native Regular / Tall rows. Edit labels and trailing controls on the exposed Apple instance.',rows);
const pg=wrapper(await native('3b87ef1ea49a69a7828be9980b45b54e9a4f1e88','Pages=1-6'),'Default',402,44,{},false);const pageSlot=pg.findAllWithCriteria({types:['SLOT']}).find(n=>n.children.length>0);if(pageSlot){for(const n of [...pageSlot.children].slice(3)){removed.push(n.id);n.remove();}pageSlot.children.forEach((n,j)=>{n.setProperties({'Is Active':j===0?'True':'False'});mutated.push(n.id);});}await family(5,'Page control','Native 3-page indicator. Select the nested page indicators to change active page.',[pg]);
const menu=wrapper(await native('d7fb78a939587c6202681d66342730d9a55607ad','Is Enabled=True'),'Default',120,44,{'Label#488:193':'Today'});await family(1,'Menu trigger','Native pop-up control for schedule selection. Options use the native menu presentation.',[menu]);
const alert=wrapper(await native('f4cc12bab154ac2830f85336b02b62532f4fd980','Button Layout=Side-by-Side'),'Default',300,180,{'Title#10448:7':'Delete Task?','Message#10448:4':'Are you sure you want to delete this task?','Show Text Field#12616:4':false});const actions=alert.findAllWithCriteria({types:['INSTANCE']}).filter(n=>'Title#452:1'in n.componentProperties);actions.forEach((n,j)=>{n.setProperties({'Title#452:1':j?'Delete':'Cancel',Role:j?'Destructive':'Cancel'});mutated.push(n.id);});rounded(alert);alert.children[0].layoutSizingVertical='HUG';alert.primaryAxisSizingMode='AUTO';await family(5,'Alert','Native delete confirmation. Destructive action is explicit; Cancel remains available.',[alert]);
const spinner=wrapper(await native('13cb29b2e39e5e06be3901901ce173d4c7e398fc','Size=Large'),'Default',35,35,{},false);await family(5,'Loading indicator','Native ProgressView spinner. Pair with a factual status and Cancel for long processing.',[spinner]);
return summary();
