// Append after common.js. Create eight independent screen compositions from this page's masters.
const M={status:'1096:407',home:'1096:424',tabHome:'1096:429',tabTasks:'1096:468',tabGoals:'1096:502',icon:'1096:540',buttonPrimary:'1096:553',buttonSecondary:'1096:556',buttonPlain:'1096:559',segmentTimeline:'1096:565',segmentCalendar:'1096:588',menu:'1096:611',field:'1096:617',toggle:'1096:624',row:'1096:632',task:'1096:663',goal:'1096:680',preview:'1096:689',editor:'1096:694',entry:'1096:699'};
const screens=[],actions=[];
async function button(parent,label,role='Primary',width=354,action){const b=await inst(M['button'+role],parent,label);b.resize(width,52);nativeText(b,label);if(action)actions.push({id:b.id,action});return b;}
async function icon(parent,glyph,action){const b=await inst(M.icon,parent,glyph);nativeSymbol(b,glyph);if(action)actions.push({id:b.id,action});return b;}
function fixed(parent,name,w,h,color){const f=stack(parent,name,w,0);f.resize(w,h);f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';if(color)fill(f,color);return f;}
function section(parent,title){const s=stack(parent,title,354,8);txt(s,title,354,'Heading');return s;}
function heading(parent,title,subtitle){const h=stack(parent,'Heading',354,6);txt(h,title,354,'Large title');if(subtitle)txt(h,subtitle,354,'Small','Secondary');return h;}
async function task(parent,title,schedule='Today',review=false){const i=await inst(M.task,parent,review?'Review task':'Task');own(i,'Title',title);const menu=i.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name==='Schedule');const native=menu.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#488:193'in n.componentProperties);native.setProperties({'Label#488:193':schedule});mutated.push(native.id);if(review){const t=i.findAllWithCriteria({types:['TEXT']}).find(n=>n.name==='SF Symbol / circle');t.characters=figma.util.getSfSymbolCharacter('minus.circle');mutated.push(t.id);}return i;}
async function goal(parent,detail='1 little step logged',action='goal'){const i=await inst(M.goal,parent);own(i,'Detail',detail);if(action)actions.push({id:i.id,action});return i;}
async function preview(parent,title,detail){const i=await inst(M.preview,parent);own(i,'Title',title);own(i,'Detail',detail);return i;}
async function screen(key,title,index,{tab=null,footer=0,navTitle='',back=null,settings=false,summary=false}={}){
 if(page.children.some(n=>n.name==='Screen / '+key))throw Error('Screen exists '+key);
 const x=160+(index%4)*474,y=1460+Math.floor(index/4)*1050;
 const label=txt(page,String(index+1).padStart(2,'0')+' / '+title,402,'Heading');label.x=x;label.y=y-44;
 const f=stack(page,'Screen / '+key,402,0);f.resize(402,874);f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';fill(f,'Canvas');f.clipsContent=true;f.x=x;f.y=y;
 await inst(M.status,f,'Status bar');
 const nav=fixed(f,'Navigation',402,44);nav.layoutMode='HORIZONTAL';nav.itemSpacing=8;nav.paddingLeft=16;nav.paddingRight=16;nav.counterAxisAlignItems='CENTER';
 if(back)await icon(nav,back==='close'?'xmark':'chevron.backward','back');else{const space=fixed(nav,'Leading space',44,44);}
 const titleNode=txt(nav,navTitle,266,'Button');titleNode.textAlignHorizontal='CENTER';titleNode.layoutSizingHorizontal='FILL';
 if(summary)await icon(nav,'sun.max','summary');if(settings)await icon(nav,'gearshape','settings');else if(key==='goal')await icon(nav,'ellipsis','goalMenu');else if(key==='capture')await icon(nav,'mic','voice');else fixed(nav,'Trailing space',44,44);
 const body=stack(f,'Scrollable content',402,24);body.paddingLeft=24;body.paddingRight=24;body.paddingTop=16;body.paddingBottom=20;body.resize(402,1);body.layoutSizingVertical='FILL';body.clipsContent=true;body.overflowDirection='VERTICAL';
 let foot=null;if(footer){foot=fixed(f,'Primary action region',402,footer);foot.paddingLeft=24;foot.paddingRight=24;foot.primaryAxisAlignItems='CENTER';}
 if(tab)await inst(M['tab'+tab],f,'Tabs');await inst(M.home,f,'Home indicator');
 const result={key,id:f.id,body:body.id,footer:foot?.id,index,title,tab};screens.push(result);return{f,body,foot,nav};
}
// 01: approachable first use, with a real capture action.
const empty=await screen('home-empty','A gentle starting point',0,{tab:'Home',settings:true});heading(empty.body,'Home');
const welcome=stack(empty.body,'Welcome',354,20);welcome.counterAxisAlignItems='CENTER';const motif=fixed(welcome,'A little sun',100,100,'Peach');motif.cornerRadius=36;motif.primaryAxisAlignItems='CENTER';motif.counterAxisAlignItems='CENTER';symbol(motif,'cloud.sun.fill',52,'Plum');
const wt=txt(welcome,'Room for what’s\non your mind.',354,'Title');wt.textAlignHorizontal='CENTER';const wd=txt(welcome,'Big plans, little errands, all the things.\nLet’s give them a place.',354,'Body','Secondary');wd.textAlignHorizontal='CENTER';await button(welcome,'Start a brain dump','Primary',354,'capture');
const concepts=stack(empty.body,'Tasks and goals',354,12,'HORIZONTAL');for(const[title,copy,color,glyph]of [['Tasks','Things to do.','Surface','checkmark.circle'],['Goals','Things to grow.','Sage','leaf']]){const c=stack(concepts,title,171,8);c.paddingLeft=16;c.paddingRight=16;c.paddingTop=16;c.paddingBottom=16;c.cornerRadius=20;fill(c,color);symbol(c,glyph,24);txt(c,title,139,'Button');txt(c,copy,139,'Small','Secondary');}
// 02: today first, then ongoing pursuits.
const home=await screen('home','A lighter day',1,{tab:'Home',footer:76,settings:true,summary:true});heading(home.body,'Home','One thing at a time.');const today=section(home.body,'For today');await task(today,'Buy groceries');const growing=section(home.body,'A little progress');await goal(growing);const day=stack(home.body,'Daily encouragement',354,12,'HORIZONTAL');day.paddingTop=16;day.paddingBottom=16;day.paddingLeft=16;day.paddingRight=16;day.cornerRadius=20;fill(day,'Peach');symbol(day,'sun.max',28);txt(day,'You made room for a little music today.',266,'Small');await button(home.foot,'Brain dump','Primary',354,'capture');
// 03: the editor comes first; the interpretation stays explicitly unsaved.
const capture=await screen('capture','Thoughts, then a preview',2,{footer:80,navTitle:'Brain dump',back:'close'});heading(capture.body,'Let it all out.','A sentence, a list, a small ramble.');await inst(M.editor,capture.body);const mode=stack(capture.body,'Processing mode',354,8,'HORIZONTAL');symbol(mode,'iphone',16,'Secondary');txt(mode,'Using local rules',320,'Caption','Secondary');const pre=section(capture.body,'Preview · not saved');pre.itemSpacing=8;await preview(pre,'Buy groceries','Task · Today');await preview(pre,'Call the dentist','Task · This Week');await preview(pre,'Guitar','New goal');await button(capture.foot,'Review 3 items','Primary',354,'review');
// 04: deliberate confirmation, editable classification and explicit save.
const review=await screen('review','Make it yours',3,{footer:80,navTitle:'Review',back:'back'});heading(review.body,'Make it yours.','2 tasks and 1 goal. Nothing saved yet.');const rt=section(review.body,'Tasks');await task(rt,'Buy groceries','Today',true);await task(rt,'Call the dentist','This Week',true);const rg=section(review.body,'New goal');await goal(rg,'A new place to keep growing',null);txt(review.body,'Tap text to edit, menus to adjust, or the minus to remove an item.',354,'Small','Secondary');await button(review.foot,'Save 3 items','Primary',354,'saved');
// 05: familiar schedule groups, no invented dates or extra destination tabs.
const tasks=await screen('tasks','Little things, in their place',4,{tab:'Tasks',footer:76,settings:true});heading(tasks.body,'Tasks','2 open tasks. Plenty of breathing room.');await task(section(tasks.body,'Today'),'Buy groceries');await task(section(tasks.body,'This Week'),'Call the dentist','This Week');const someday=section(tasks.body,'Someday');txt(someday,'Nothing waiting here. That’s okay.',354,'Small','Secondary');await button(tasks.foot,'Brain dump','Primary',354,'capture');
// 06: ongoing pursuits with factual progress, not productivity scores.
const goals=await screen('goals','Things you’re growing',5,{tab:'Goals',footer:76,settings:true});heading(goals.body,'Goals','Things you’re growing, at your pace.');await goal(goals.body);const note=stack(goals.body,'What is a goal?',354,12);note.paddingTop=24;note.paddingBottom=24;note.paddingLeft=24;note.paddingRight=24;note.cornerRadius=24;fill(note,'Sage');symbol(note,'leaf',32);txt(note,'No finish line required.',306,'Heading');txt(note,'A little practice. A new interest.\nCome back whenever you’re ready.',306,'Body','Secondary');await button(goals.foot,'Brain dump','Primary',354,'capture');
// 07: native picker and clear progress actions, factual sparse-data state.
const detail=await screen('goal','A little step counts',6,{tab:'Goals',footer:76,navTitle:'Guitar',back:'back'});const hero=stack(detail.body,'Goal introduction',354,12);hero.paddingTop=24;hero.paddingBottom=24;hero.paddingLeft=24;hero.paddingRight=24;hero.cornerRadius=24;fill(hero,'Lilac');symbol(hero,'guitars',36);txt(hero,'A little more music.',306,'Title');txt(hero,'1 entry · Started today',306,'Small','Secondary');await inst(M.segmentTimeline,detail.body,'Timeline / Calendar');await inst(M.entry,section(detail.body,'Today'));txt(detail.body,'A small step still counts.',354,'Small','Secondary');const progress=stack(detail.foot,'Log progress',354,8,'HORIZONTAL');await button(progress,'Did something today','Primary',302,'quickEntry');await icon(progress,'square.and.pencil','note');
// 08: clear mode and persistent labels; lower preferences scroll naturally.
const settings=await screen('settings','Your app, your way',7,{navTitle:'Settings',back:'close'});heading(settings.body,'Make yourself at home.');const local=stack(settings.body,'Current processing',354,10);local.paddingTop=18;local.paddingBottom=18;local.paddingLeft=18;local.paddingRight=18;local.cornerRadius=20;fill(local,'Sage');txt(local,'Local rules are on',318,'Heading');txt(local,'Add your own model below when you want to. Typing works either way.',318,'Small','Secondary');
const model=section(settings.body,'Your model');for(const[label,value,state]of [['Endpoint URL','https://openrouter.ai/api/v1/chat/…','Value Entered'],['API key','Enter your key','Placeholder'],['Model ID','openai/gpt-4o-mini','Value Entered']]){const group=stack(model,label,354,2);txt(group,label,354,'Caption','Secondary');const field=await inst(M.field,group,label+' field');const n=field.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Value#519:17'in n.componentProperties);n.setProperties({State:state,'Value#519:17':value});mutated.push(n.id);}
txt(model,'Compatible with OpenAI-style APIs. A configured provider receives the text you ask it to process.',354,'Small','Secondary');const test=await button(model,'Test connection','Secondary');const bn=test.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Is Enabled'in n.componentProperties);bn.setProperties({'Is Enabled':'False'});mutated.push(bn.id);const pref=section(settings.body,'Preferences');
for(const[label,glyph]of [['Dark appearance','moon'],['Gentle reminders','bell']]){const row=stack(pref,label,354,12,'HORIZONTAL');row.paddingTop=12;row.paddingBottom=12;row.paddingLeft=16;row.paddingRight=16;row.cornerRadius=16;fill(row,'Surface');row.counterAxisAlignItems='CENTER';txt(row,label,234,'Body');await inst(M.toggle,row);}
for(const[label,detailText]of [['Storage','This device'],['Archived goals',''],['App tour','']]){const row=await inst(M.row,pref,label);const n=row.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Title#519:116'in n.componentProperties);n.setProperties({'Title#519:116':label});const tr=n.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Detail Text#508:54'in n.componentProperties);tr.setProperties({'Detail Text#508:54':detailText});mutated.push(n.id,tr.id);}
// Context notes outside devices keep prototype limitations out of product copy.
const noteBoard=stack(page,'Exploration notes',1824,12);noteBoard.x=160;noteBoard.y=3460;noteBoard.paddingTop=24;noteBoard.paddingBottom=24;noteBoard.paddingLeft=24;noteBoard.paddingRight=24;fill(noteBoard,'Surface');txt(noteBoard,'What this pass explores',1776,'Heading');txt(noteBoard,'Cute through Rounded type, warm surfaces and small SF Symbols. Native controls retain their full bounds. Current task/goal semantics remain; capture, review and save labels are proposed improvements.',1776,'Body');txt(noteBoard,'Eight screens only. Keyboard, voice permission, processing/cancel, no-result, completion/goal-update review, Calendar, progress editing, Daily Summary, archive/delete, storage migration and connection failures still need dedicated states. Unwired controls are visual specimens. Source risks are not resolved by this prototype.',1776,'Small','Secondary');
return summary({screens,actions,notesId:noteBoard.id,regions:screens.map(s=>{const f=page.findOne(n=>n.id===s.id);return{key:s.key,id:s.id,children:f.children.map(n=>({id:n.id,name:n.name,y:n.y,h:n.height}))};})});
