// Append after common.js. Fresh local masters; no cloning of prior screen designs.
if(page.children.some(n=>n.name==='Design system'))throw Error('System already exists');
const board=stack(page,'Design system',1824,24);board.x=160;board.y=160;board.paddingTop=32;board.paddingBottom=32;board.paddingLeft=32;board.paddingRight=32;fill(board,'Surface');
txt(board,'defog · a little room to breathe',1760,'Large title');txt(board,'REDESIGN 1 BY AI  /  Native iOS, a softer personality  /  Exploration for review',1760,'Caption','Secondary');
const colors=stack(board,'Palette',1760,16,'HORIZONTAL');for(const name of ['Canvas','Surface','Ink','Secondary','Plum','Lilac','Peach','Sage']){const sw=stack(colors,name,206,8);const block=keep(figma.createFrame());sw.appendChild(block);block.resize(206,40);block.cornerRadius=10;fill(block,name);if(name==='Surface'){block.strokes=[paint('Canvas')];block.strokeWeight=1;}txt(sw,name+' · '+C[name],206,'Caption','Secondary');}
const type=stack(board,'Type and rhythm',1760,24,'HORIZONTAL');txt(type,'Ready when you are.',480,'Title');txt(type,'SF Pro Rounded · titles, headings, buttons\nSF Pro · body, input, device chrome',620,'Small','Secondary');txt(type,'Spacing 8 / 12 / 16 / 24 / 32\nSoft content corners 20 · native control shapes',600,'Small','Secondary');
const grid=stack(board,'Component library',1760,36,'HORIZONTAL');const cols=[0,1,2].map(i=>stack(grid,['Native navigation','Native controls','Defog content'][i],560,18));cols.forEach((c,i)=>txt(c,['01 / Navigation','02 / Controls','03 / Content'][i],560,'Heading'));
const M={},families=[];
function show(col,label,n,note){const group=stack(cols[col],label,560,8);txt(group,label,560,'Caption','Secondary');group.appendChild(n);if(note)txt(group,note,520,'Caption','Secondary');families.push({name:label,id:n.id});}
const status=await figma.importComponentByKeyAsync('e01a1714aeec1a5a0a6453485bf16e975008b282');await fonts(status);M.status=await wrap(status,'Status bar',402,62,{'Time#5466:4':'9:41'});show(0,'Status bar',M.status);
M.home=await wrap(await variant('db1fd2b84f66cfc75ab693b5b0b77b90ae471e38','Device=iPhone, Orientation=Portrait'),'Home indicator',402,34);show(0,'Home indicator',M.home);
const tabs=[];for(const name of ['Home','Tasks','Goals']){const c=await wrap(await variant('971f4862d60ea7fb60429ff57f4e51dc42758f6a','Minimized=False, Tabs=3, Type=Default'),'Selected='+name,402,95);c.name='Selected='+name;const native=c.children[0];const items=native.findAllWithCriteria({types:['INSTANCE']}).filter(n=>'Label#5735:10'in n.componentProperties);for(let j=0;j<items.length;j++){items[j].setProperties({'Label#5735:10':['Home','Tasks','Goals'][j],'Symbol#5735:9':figma.util.getSfSymbolCharacter(['house.fill','checkmark.circle.fill','leaf.fill'][j]),Selected:name===['Home','Tasks','Goals'][j]?'True':'False'});mutated.push(items[j].id);}rounded(native,'Medium');tint(native);native.resize(402,95);native.layoutSizingVertical='FIXED';tabs.push(c);M['tab'+name]=c;}
const tabSet=keep(figma.combineAsVariants(tabs,page));tabSet.name='AI1 / Tab bar';tabs.forEach((c,i)=>{c.x=8;c.y=8+i*111;});tabSet.resize(418,341);show(0,'Three destinations',tabSet,'Capture is a separate action. Full tab slot 95pt; home slot 34pt.');
M.icon=await wrap(await variant('36df7438d67ed37c94488fd11d425899f1a902ba','Style=Glass, Is Enabled=True, Destructive=False'),'Icon action',44,44);nativeSymbol(M.icon,'plus');show(0,'Navigation action',M.icon,'Attached Apple glass button. Edit nested symbol property.');
const buttons=[];for(const[role,style]of [['Primary','Bordered - Prominent'],['Secondary','Bordered'],['Plain','Borderless']]){const c=await wrap(await variant('bba76d7e88d66c8704a07953ccc6056a185022b0',`Size=Large, Style=${style}, Label Style=Title only, Is Enabled=True, Destructive=False`),'Role='+role,354,52,{'Label#488:0':'Brain dump'},true);c.name='Role='+role;buttons.push(c);M['button'+role]=c;}
const bs=keep(figma.combineAsVariants(buttons,page));bs.name='AI1 / Button';buttons.forEach((c,i)=>{c.x=8;c.y=8+i*64;});bs.resize(370,200);show(1,'Buttons',bs);
const seg=[];for(const selected of ['Timeline','Calendar']){const c=await wrap(await variant('f508912e2177f4744038dc6591e976abf1040806','Size=Small, Is Enabled=True'),'Selected='+selected,354,32);c.name='Selected='+selected;const slot=c.findAllWithCriteria({types:['SLOT']}).find(n=>n.name==='Segments');for(const n of [...slot.children].slice(2)){removed.push(n.id);n.remove();}slot.children.forEach((n,j)=>{n.setProperties({'Title#10512:0':j?'Calendar':'Timeline','Is Selected':selected===(j?'Calendar':'Timeline')?'True':'False'});mutated.push(n.id);});c.children[0].opacity=1;rounded(c,'Medium');seg.push(c);M['segment'+selected]=c;}
const sg=keep(figma.combineAsVariants(seg,page));sg.name='AI1 / Segmented control';seg.forEach((c,i)=>{c.x=8;c.y=8+i*48;});sg.resize(370,96);show(1,'Native segmented control',sg);
M.menu=await wrap(await variant('d7fb78a939587c6202681d66342730d9a55607ad','Is Enabled=True'),'Menu',124,44,{'Label#488:193':'Today'},true);show(1,'Schedule / goal menu',M.menu);
M.field=await wrap(await variant('38117a30dd18e50d4c086b01121258a32567f920','State=Value Entered'),'Text field',354,52,{'Value#519:17':'openai/gpt-4o-mini'});show(1,'Text field',M.field);
M.toggle=await wrap(await variant('62c79e1affadacf2e24597674ca46f1806d32ffc','State=Idle, Is On=False, Is Enabled=True'),'Switch',64,28,{'Show AX Label#6152:0':false});show(1,'Switch',M.toggle,'Use inside a row with a full native hit area.');
M.row=await wrap(await variant('da6c778eb113a68c7fd6f3828741ab33c3ec8f12','Height=Regular'),'Settings row',354,52,{'Title#519:116':'App tour','Show Subtitle#525:450':false},true);const trailing=M.row.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Detail Text#508:54'in n.componentProperties);trailing.setProperties({'Detail Text#508:54':'','Show Symbol#212:5':false,'Show Drill-in#212:3':true});mutated.push(trailing.id);show(1,'Native list row',M.row);
M.task=comp('Task row',354,4);M.task.paddingTop=12;M.task.paddingBottom=10;M.task.paddingLeft=16;M.task.paddingRight=16;M.task.cornerRadius=20;fill(M.task,'Surface');const taskLine=stack(M.task,'Task title',322,12,'HORIZONTAL');taskLine.counterAxisAlignItems='CENTER';const circle=symbol(taskLine,'circle',24,'Secondary');circle.resize(28,28);const taskTitle=txt(taskLine,'Buy groceries',234,'Body');prop(M.task,taskTitle,'Title');symbol(taskLine,'ellipsis',18,'Secondary');const menus=stack(M.task,'Task metadata',322,8,'HORIZONTAL');const schedule=await inst(M.menu,menus,'Schedule');schedule.resize(112,44);const goalMenu=await inst(M.menu,menus,'Goal link');goalMenu.resize(156,44);const gm=goalMenu.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Label#488:193'in n.componentProperties);gm.setProperties({'Label#488:193':'No goal'});mutated.push(gm.id);show(2,'Task row',M.task,'Editable title; native schedule and goal menus.');
M.goal=comp('Goal card',354,12,'HORIZONTAL');M.goal.paddingTop=20;M.goal.paddingBottom=20;M.goal.paddingLeft=20;M.goal.paddingRight=20;M.goal.cornerRadius=20;fill(M.goal,'Lilac');M.goal.counterAxisAlignItems='CENTER';const badge=stack(M.goal,'Goal symbol',48,0);badge.resize(48,48);badge.primaryAxisSizingMode='FIXED';badge.primaryAxisAlignItems='CENTER';badge.counterAxisAlignItems='CENTER';badge.cornerRadius=16;fill(badge,'Surface');symbol(badge,'guitars',26);const labels=stack(M.goal,'Goal content',226,4);prop(M.goal,txt(labels,'Guitar',226,'Heading'),'Title');prop(M.goal,txt(labels,'1 little step logged',226,'Small','Secondary'),'Detail');symbol(M.goal,'chevron.right',14,'Plum');show(2,'Goal card',M.goal);
M.preview=comp('Preview item',354,4);M.preview.paddingTop=12;M.preview.paddingBottom=12;M.preview.paddingLeft=16;M.preview.paddingRight=16;M.preview.cornerRadius=16;fill(M.preview,'Surface');prop(M.preview,txt(M.preview,'Buy groceries',322,'Body'),'Title');prop(M.preview,txt(M.preview,'Task · Today',322,'Caption','Secondary'),'Detail');show(2,'Unsaved preview item',M.preview);
M.editor=comp('Thought editor',354,12);M.editor.paddingTop=18;M.editor.paddingBottom=18;M.editor.paddingLeft=18;M.editor.paddingRight=18;M.editor.cornerRadius=20;fill(M.editor,'Surface');const entry=txt(M.editor,'Buy groceries today. Call the dentist this week. I’d like to learn guitar.',318,'Body');entry.resize(318,104);entry.textAutoResize='NONE';prop(M.editor,entry,'Thoughts');show(2,'Multiline thought editor',M.editor,'Defog TextEditor composition; typing and keyboard behavior need implementation.');
M.entry=comp('Timeline entry',354,8,'HORIZONTAL');M.entry.paddingTop=16;M.entry.paddingBottom=16;M.entry.paddingLeft=16;M.entry.paddingRight=16;M.entry.cornerRadius=20;fill(M.entry,'Surface');symbol(M.entry,'checkmark.circle.fill',24,'Plum');const et=stack(M.entry,'Entry text',274,4);prop(M.entry,txt(et,'Showed up for guitar',274,'Button'),'Title');prop(M.entry,txt(et,'Today, 9:04 PM · Quick entry',274,'Caption','Secondary'),'Detail');show(2,'Progress entry',M.entry);
txt(board,'Edit these local mains to update the screens below. Native components stay attached. Light-mode exploration; full tokenization and accessibility validation follow after direction approval.',1760,'Small','Secondary');
return summary({boardId:board.id,boardHeight:board.height,masters:Object.fromEntries(Object.entries(M).map(([k,n])=>[k,n.id])),families});
