// Prepend common.js. Proposal, fixed synthetic input; never application code.
figma.skipInvisibleInstanceChildren=false;C.Forest='#326B59';
const routes={},links=[];const variables={};
const collection=figma.variables.createVariableCollection('Redesign Two / Manual creation');
function variable(name,type,value){const v=figma.variables.createVariable(name,collection,type);v.scopes=type==='BOOLEAN'?['ALL_SCOPES']:['TEXT_CONTENT'];v.hiddenFromPublishing=true;v.setValueForMode(collection.defaultModeId,value);variables[name]=v;return v;}
const vGoal=variable('draftGoal','STRING','No goal'),vSchedule=variable('draftSchedule','STRING','Today'),vDate=variable('draftDate','STRING','None'),vSaved=variable('taskSaved','BOOLEAN',false),vCreated=variable('goalCreated','BOOLEAN',false),vContext=variable('goalFromTask','BOOLEAN',false),vDated=variable('hasDate','BOOLEAN',false);
const literal=(value,type='STRING')=>({type,resolvedType:type,value});
const set=(v,value)=>({type:'SET_VARIABLE',variableId:v.id,variableValue:literal(value,v.resolvedType)});
const eq=(v,value)=>({type:'EXPRESSION',resolvedType:'BOOLEAN',value:{expressionFunction:'EQUALS',expressionArguments:[{type:'VARIABLE_ALIAS',resolvedType:v.resolvedType,value:{type:'VARIABLE_ALIAS',id:v.id}},{type:v.resolvedType,resolvedType:v.resolvedType,value}]}});
const nav=id=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:true});
function target(n,to,extra=[]){links.push({n,to,extra});return n;}
function box(parent,name,w=354,gap=0){const n=stack(parent,name,w,gap);fill(n,'Surface');n.cornerRadius=20;n.clipsContent=true;return n;}
function clear(n){for(const x of [...n.children]){removed.push(x.id);x.remove();}mutated.push(n.id);}
async function cleanReactions(n){for(const x of [n,...n.findAll(()=>true)])if('reactions'in x&&x.reactions.length){await x.setReactionsAsync([]);mutated.push(x.id);}}
async function button(p,label,to,role='Plain',w=354,extra=[]){const i=await inst(M['button'+role],p,label);await cleanReactions(i);i.resize(w,52);nativeText(i,label);if(to)target(i,to,extra);return i;}
async function row(p,label,detail='',to=null,{varr=null,type='Default',last=false,extra=[]}={}){const i=await inst(M.row,p,label);await cleanReactions(i);const native=i.children[0];native.setProperties({'Title#519:116':label});const acc=native.findAllWithCriteria({types:['INSTANCE']}).find(n=>'Detail Text#508:54'in n.componentProperties);await fonts(await figma.getNodeByIdAsync(type==='Picker - Date'?'1025:884':type==='Picker - Time'?'1025:885':'1025:889'));acc.setProperties({Type:type,'Detail Text#508:54':detail,'Show Drill-in#212:3':!!to,'Show Checkmark#212:4':false});if(varr)acc.setProperties({'Detail Text#508:54':{type:'VARIABLE_ALIAS',id:varr.id}});if(last)for(const s of i.findAll(x=>/separator/i.test(x.name)))s.visible=false;if(to)target(i,to,extra);mutated.push(native.id,acc.id);return i;}
async function field(p,value,placeholder=false,to=null){const f=await inst(M.field,p,'Title input');await cleanReactions(f);f.children[0].setProperties({State:placeholder?'Placeholder':'Value Entered','Value#519:17':value});mutated.push(f.children[0].id);if(to)target(f,to);return f;}
function section(p,title){const s=stack(p,title,354,8);const label=stack(s,'Label inset',354,0);label.paddingLeft=16;label.paddingRight=16;txt(label,title,322,'Caption','Secondary');return s;}
function helper(p,value){const s=stack(p,'Help',354,0);s.paddingLeft=16;s.paddingRight=16;return txt(s,value,322,'Small','Secondary');}
function absolute(n,x,y,w,h){n.layoutPositioning='ABSOLUTE';n.resize(w,h);n.x=x;n.y=y;mutated.push(n.id);}
async function screen(key,title,index,back='filled',save=null){const f=stack(page,'R2 / '+key,402,0);f.resize(402,874);f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';f.x=8160+(index%5)*474;f.y=8500+Math.floor(index/5)*1050;fill(f,'Canvas');f.clipsContent=true;routes[key]=f.id;
 const cap=txt(page,title+' · '+key,402,'Heading');cap.x=f.x;cap.y=f.y-44;
 await inst(M.status,f,'Status bar');const n=stack(f,'Navigation',402,8,'HORIZONTAL');n.resize(402,52);n.counterAxisAlignItems='CENTER';n.paddingLeft=8;n.paddingRight=8;await button(n,back==='home'?'Cancel':'Back',back,'Plain',76);const t=txt(n,title,194,'Button');t.textAlignHorizontal='CENTER';t.layoutSizingHorizontal='FILL';if(save)await button(n,'Save',save,'Plain',76);else{const sp=stack(n,'Trailing space',76,0);sp.resize(76,44);}
 const b=stack(f,'Form content',402,24);b.paddingLeft=24;b.paddingRight=24;b.paddingTop=24;b.paddingBottom=24;b.resize(402,1);b.layoutSizingVertical='FILL';b.clipsContent=true;b.overflowDirection='VERTICAL';await inst(M.home,f,'Home indicator');return{f,b,n};}
const board=stack(page,'Redesign Two / Manual creation components',1760,24);board.x=13300;board.y=8500;board.paddingLeft=32;board.paddingRight=32;board.paddingTop=32;board.paddingBottom=32;fill(board,'Canvas');txt(board,'Create it directly',1696,'Large title');txt(board,'Tasks and goals. Brain Dump is optional.',1696,'Heading');txt(board,'Editable local components • native Apple controls • fixed sample data in this prototype',1696,'Small','Secondary');
// These four reusable form masters are shown beside their actual screen instances.
const masters={};
for(const [name,filled]of [['Task empty',false],['Task filled',true]]){const c=comp(name,354,24);board.appendChild(c);c.name='AI2 / '+name;c.description='Manual task form. Date and time are disclosed from Schedule. Local master; prototype uses fixed synthetic input.';const title=section(c,'Task');await field(box(title,'Title'),filled?'Sketch for 10 minutes':'What do you need to do?',!filled);const details=section(c,'Details');const group=box(details,'Task options');await row(group,'Schedule','',null,{varr:vSchedule});await row(group,'Goal','',null,{varr:vGoal,last:true});masters[name]=c;}
for(const [name,filled]of [['Goal empty',false],['Goal filled',true]]){const c=comp(name,354,24);board.appendChild(c);c.name='AI2 / '+name;c.description='Direct goal creation. Short activity name; optional symbol. Saving from task picker returns to the task draft.';const title=section(c,'Goal name');await field(box(title,'Title'),filled?'Draw':'For example, Draw',!filled);const details=section(c,'Appearance');const group=box(details,'Goal options');await row(group,'Symbol','􀈊',null,{last:true});helper(c,'You can link tasks and record progress after creating the goal.');masters[name]=c;}
const alternatives=stack(board,'Owner alternatives',1696,24,'HORIZONTAL');for(const label of ['Your task form','Your goal form']){const a=stack(alternatives,label,800,12);a.resize(800,360);a.primaryAxisSizingMode='FIXED';a.strokes=[paint('Secondary')];a.dashPattern=[6,6];a.cornerRadius=20;a.paddingLeft=24;a.paddingTop=24;txt(a,label,752,'Heading');}
// An additional green pill keeps task/goal identity consistent when a new goal is created.
const originalPill=await figma.getNodeByIdAsync(M.pillGuitar);await fonts(originalPill);const drawPill=keep(originalPill.clone());originalPill.parent.appendChild(drawPill);drawPill.name='Kind=Draw';drawPill.x=originalPill.x;drawPill.y=originalPill.parent.height+16;for(const t of drawPill.findAllWithCriteria({types:['TEXT']}))if(t.characters==='Guitar'){t.characters='Draw';mutated.push(t.id);}
// Main navigation gains explicit creation controls; the existing bodies remain intact.
routes.home=roots['1097:589'];routes.tasks=roots['1097:823'];routes.goals=roots['1097:919'];routes.capture=roots['1118:6207'];routes.ready=roots['1165:2970'];
for(const [key,isGoal]of [['home',false],['tasks',false],['goals',true]]){const f=await figma.getNodeByIdAsync(routes[key]);await fonts(f);const b=f.children.find(n=>n.name==='Scrollable content');const btn=await button(b,isGoal?'New goal':'New task',isGoal?'goal-empty':'empty','Secondary',354,isGoal?[set(vContext,false)]:[set(vGoal,'No goal'),set(vSchedule,'Today'),set(vDate,'None'),set(vDated,false)]);b.insertChild(1,btn);const guide=f.children.find(n=>n.name==='Guidance region');if(guide){guide.visible=false;mutated.push(guide.id);}const fade=f.children.find(n=>n.name==='Bottom scroll edge');if(fade)absolute(fade,0,701,402,139);const tail=stack(b,'Bottom safe-area clearance',354,0);tail.resize(354,146);tail.primaryAxisSizingMode='FIXED';mutated.push(b.id);}
const empty=await screen('empty','New task',0,'home');const emptyInst=await inst(masters['Task empty'],empty.b,'Task form');target(emptyInst.findOne(n=>n.name==='Title input'),'filled');const dis=await button(empty.n,'Save',null,'Plain',76);empty.n.children[2].remove();dis.children[0].setProperties({'Is Enabled':'False'});mutated.push(dis.children[0].id);
const filled=await screen('filled','New task',1,'leave-task','tasks');const form=await inst(masters['Task filled'],filled.b,'Task form');target(form.findOne(n=>n.name==='Schedule'),'schedule');target(form.findOne(n=>n.name==='Goal'),'goal-picker');const dateLabel=helper(filled.b,'');dateLabel.setBoundVariable('characters',vDate);dateLabel.setBoundVariable('visible',vDated);target(filled.n.children.find(n=>n.name==='Save'),'tasks',[set(vSaved,true)]);
const schedule=await screen('schedule','Schedule',2,'filled');const g=box(schedule.b,'Schedule choices');for(const label of ['Today','This Week','Someday'])await row(g,label,'','filled',{last:label==='Someday',extra:[set(vSchedule,label),set(vDate,'None'),set(vDated,false)]});const dt=section(schedule.b,'Optional');await row(box(dt,'Date option'),'Date & time','', 'date');helper(schedule.b,'Choose a specific date or time when you need one.');
const date=await screen('date','Date & time',3,'schedule');const dates=box(date.b,'Date and time');const dr=await row(dates,'Date','',null,{type:'Picker - Date'});const ti=await row(dates,'Time','',null,{type:'Picker - Time',last:true});for(const rr of [dr,ti])for(const i of rr.findAllWithCriteria({types:['INSTANCE']}))if('Time#30:4'in i.componentProperties){await fonts(i);i.setProperties({'Month#30:0':'Oct 2,','Year#30:2':'2026','Time#30:4':'9:00 AM'});mutated.push(i.id);}helper(date.b,'A date is enough. Add a time if you want an alert.');await button(date.b,'Use date & time','filled','Primary',354,[set(vDate,'Oct 2 · 9:00 AM'),set(vDated,true),set(vSchedule,'This Week')]);await button(date.b,'Use date only','filled','Plain',354,[set(vDate,'Oct 2'),set(vDated,true),set(vSchedule,'This Week')]);await button(date.b,'Remove date','filled','Plain',354,[set(vDate,'None'),set(vDated,false)]);
const picker=await screen('goal-picker','Link a goal',4,'filled');const opts=box(picker.b,'Goal choices');for(const name of ['No goal','Guitar','Read','Run'])await row(opts,name,'','filled',{extra:[set(vGoal,name)],last:name==='Run'});await button(picker.b,'New goal','goal-empty','Secondary',354,[set(vContext,true)]);
const ge=await screen('goal-empty','New goal',5,'goal-cancel');const gei=await inst(masters['Goal empty'],ge.b,'Goal form');target(gei.findOne(n=>n.name==='Title input'),'goal-filled');const gf=await screen('goal-filled','New goal',6,'goal-cancel','goal-save');await inst(masters['Goal filled'],gf.b,'Goal form');
const leave=await screen('leave-task','Keep this task?',7,'filled');txt(leave.b,'Your task hasn’t been saved.',354,'Title');helper(leave.b,'Keep editing, or discard this draft.');await button(leave.b,'Keep editing','filled','Primary');await button(leave.b,'Discard draft','home','Secondary',354,[set(vGoal,'No goal'),set(vSchedule,'Today'),set(vDated,false)]);
const gd=await screen('draw','Draw',8,'goals');symbol(gd.b,'pencil',42,'Forest');txt(gd.b,'Draw',354,'Large title');const actions=box(gd.b,'Goal actions');await row(actions,'New task','', 'empty',{extra:[set(vGoal,'Draw'),set(vSchedule,'Today'),set(vDated,false)]});await row(actions,'Record progress','',roots['1122:2113'],{last:true});helper(gd.b,'Tasks linked to this goal appear here.');
// New task instances are in both Home and Tasks; a Boolean save prevents duplicates.
for(const key of ['home','tasks','draw']){const f=await figma.getNodeByIdAsync(routes[key]);const b=f.children.find(n=>n.name==='Scrollable content'||n.name==='Form content');const task=await inst(M.task,b,'Manually created task');await cleanReactions(task);own(task,'Title','Sketch for 10 minutes');task.setBoundVariable('visible',vSaved);const sch=task.findOne(n=>n.name==='Schedule'),goal=task.findOne(n=>n.name==='Goal link');sch.setProperties({Kind:{type:'VARIABLE_ALIAS',id:vSchedule.id}});goal.setProperties({Kind:{type:'VARIABLE_ALIAS',id:vGoal.id}});target(sch,'schedule');target(goal,'goal-picker');target(task.findOne(n=>n.name==='More actions'),'filled');const complete=task.findOne(n=>n.name==='Complete task');links.push({n:complete,to:null,extra:[set(vSaved,false)]});if(key!=='draw')b.insertChild(2,task);}
const goalsRoot=await figma.getNodeByIdAsync(routes.goals);const goalsBody=goalsRoot.children.find(n=>n.name==='Scrollable content');const goalItem=await inst(M.goal,goalsBody,'Draw');await cleanReactions(goalItem);own(goalItem,'Title','Draw');own(goalItem,'Detail','No entries yet');own(goalItem,'Symbol',figma.util.getSfSymbolCharacter('pencil'));goalItem.setBoundVariable('visible',vCreated);target(goalItem,'draw');goalsBody.insertChild(2,goalItem);
// Onboarding ends in everyday Home; AI is optional in this direction.
const storage=await figma.getNodeByIdAsync(roots['1118:6135']);for(const n of storage.findAll(x=>'reactions'in x&&x.reactions.length)){const rr=JSON.parse(JSON.stringify(n.reactions));let changed=false;function fix(a){for(const x of a){if(x.type==='NODE'&&x.destinationId===routes.capture){x.destinationId=routes.home;changed=true;}if(x.type==='CONDITIONAL')for(const b of x.conditionalBlocks)fix(b.actions);}}for(const r of rr){delete r.action;fix(r.actions||[]);}if(changed){await n.setReactionsAsync(rr);mutated.push(n.id);}}
// Canvas labels make the copies and the prototype limitations explicit.
for(const [x,title,sub]of [[160,'Preserved · Redesign 1','Full snapshot. Edit the working copy on the right.'],[8160,'Working · Redesign Two','Direct task and goal creation · optional Brain Dump']]){const t=txt(page,title,1800,'Large title');t.x=x;t.y=-120;const s=txt(page,sub,1800,'Body','Secondary');s.x=x;s.y=-64;}
const note=txt(board,'Prototype walkthrough: tap a title field to fill the example. Native date/time controls show a fixed sample; free typing, date selection, alert permissions and persistence need implementation. No data is stored by this prototype.',1696,'Body','Secondary');
for(const l of links){let acts=[...l.extra];if(l.to==='goal-save'){acts.push(set(vCreated,true),{type:'CONDITIONAL',conditionalBlocks:[{condition:eq(vContext,true),actions:[set(vGoal,'Draw'),nav(routes.filled)]},{actions:[nav(routes.goals)]}]});}else if(l.to==='goal-cancel'){acts.push({type:'CONDITIONAL',conditionalBlocks:[{condition:eq(vContext,true),actions:[nav(routes['goal-picker'])]},{actions:[nav(routes.goals)]}]});}else if(l.to)acts.push(nav(routes[l.to]||l.to));await l.n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:acts}]);mutated.push(l.n.id);}
page.flowStartingPoints=[{nodeId:routes.home,name:'Redesign Two · start here'},...page.flowStartingPoints.filter(x=>!x.name.startsWith('Working'))];
return summary({routes,masters:Object.fromEntries(Object.entries(masters).map(([k,n])=>[k,n.id])),board:board.id,variables:Object.fromEntries(Object.entries(variables).map(([k,v])=>[k,v.id])),links:links.length});
