// Prepend common.js. Static native label variants avoid stale nested text overrides in Player.
figma.skipInvisibleInstanceChildren=false;C.Forest='#326B59';
const board=stack(page,'Redesign Two / Interactive label components',1400,24);board.x=13300;board.y=13300;board.paddingLeft=24;board.paddingTop=24;board.paddingBottom=24;fill(board,'Canvas');txt(board,'Interactive labels',1352,'Title');txt(board,'Native row variants and count variants share the same controls. Change the main components to update the screens.',1352,'Body','Secondary');
async function rowSet(label,values,variableId){const variants=[];for(const value of values){const c=comp(label,354,0);board.appendChild(c);c.name='Value='+value;c.description='Native Apple row with a static detail label; used as a variant because Player retains nested text overrides.';const i=await inst(M.row,c,'Native '+label+' / '+value);const native=i.children[0];native.setProperties({'Title#519:116':label});const a=native.findAllWithCriteria({types:['INSTANCE']}).find(x=>'Detail Text#508:54'in x.componentProperties);a.setProperties({'Detail Text#508:54':value,'Show Drill-in#212:3':true});for(const t of a.findAllWithCriteria({types:['TEXT']})){t.setBoundVariable('characters',null);t.name=label+' / '+value+' / '+t.name;mutated.push(t.id);}variants.push(c);}const set=keep(figma.combineAsVariants(variants,board));set.name='AI2 / '+label+' selection';set.layoutMode='VERTICAL';set.itemSpacing=8;set.primaryAxisSizingMode='AUTO';set.counterAxisSizingMode='AUTO';const variable=await figma.variables.getVariableByIdAsync(variableId);for(const id of ['1239:5907','1239:5974']){const form=await figma.getNodeByIdAsync(id);await fonts(form);const row=form.findOne(n=>n.type==='INSTANCE'&&n.name===label);row.swapComponent(variants[0]);row.setProperties({Value:{type:'VARIABLE_ALIAS',id:variable.id}});mutated.push(row.id);}return set.id;}
const goal=rowSet('Goal',['No goal','Guitar','Read','Run','Draw'],'VariableID:1239:5896');const goalSet=await goal;const scheduleSet=await rowSet('Schedule',['Today','This Week','Someday'],'VariableID:1239:5897');
async function counts(kind,values,sourceId){const original=await figma.getNodeByIdAsync(sourceId);await fonts(original);const variants=[];for(const value of values){const c=keep(original.clone());board.appendChild(c);c.name='Value='+value;for(const t of c.findAllWithCriteria({types:['TEXT']})){if(/^\d+$/.test(t.characters)){t.componentPropertyReferences={};t.setBoundVariable('characters',null);t.characters=String(value);t.name='Count / '+value;mutated.push(t.id);}}const owner=c.parent?.type==='COMPONENT_SET'?c.parent:c;for(const [key,p]of Object.entries(owner.componentPropertyDefinitions))if(p.type==='TEXT')owner.deleteComponentProperty(key);variants.push(c);}const set=keep(figma.combineAsVariants(variants,board));set.name='AI2 / '+kind+' count';set.layoutMode='HORIZONTAL';set.itemSpacing=16;set.primaryAxisSizingMode='AUTO';set.counterAxisSizingMode='AUTO';return{set,variants};}
const tasks=await counts('Task',Array.from({length:12},(_,i)=>i),M.countTask);const goals=await counts('Goal',[0,1,2,3,4],M.countGoal);
for(const [id,kind,varId]of [['1228:4475','Task','VariableID:1235:17269'],['1228:4560','Task','VariableID:1235:17269'],['1228:4476','Goal','VariableID:1242:6693'],['1228:4624','Goal','VariableID:1242:6693'],['1228:4536','Task','VariableID:1235:17270'],['1228:4537','Goal','VariableID:1241:6514']]){const n=await figma.getNodeByIdAsync(id);if(n?.type==='INSTANCE'){n.swapComponent((kind==='Task'?tasks:goals).variants[0]);n.setProperties({Value:{type:'VARIABLE_ALIAS',id:varId}});mutated.push(id);}}
// One goal title, with a small symbol in navigation.
const draw=await figma.getNodeByIdAsync('1239:7088');await fonts(draw);const body=draw.children.find(n=>n.name==='Form content');const symbolNode=body.children.find(n=>n.type==='TEXT'&&n.name.startsWith('SF Symbol'));if(symbolNode){removed.push(symbolNode.id);symbolNode.remove();}const nav=draw.children.find(n=>n.name==='Navigation').children.find(n=>n.type==='TEXT');nav.fontName={family:'SF Pro',style:'Regular'};nav.fontSize=26;nav.characters=figma.util.getSfSymbolCharacter('pencil');fill(nav,'Forest');mutated.push(nav.id);
return summary({board:board.id,goalSet,scheduleSet,taskCount:tasks.set.id,goalCount:goals.set.id});
