// Prepend common.js. Address Muse review and visual findings on working copy only.
figma.skipInvisibleInstanceChildren=false;C.Forest='#326B59';
const all=await figma.variables.getLocalVariablesAsync();const d=Object.fromEntries(all.filter(v=>v.variableCollectionId==='VariableCollectionId:1239:5895').map(v=>[v.name,v]));
// Resolve by the recorded variable rather than assuming collection identity.
const draft=await figma.variables.getVariableByIdAsync('VariableID:1239:5896');const col=await figma.variables.getVariableCollectionByIdAsync(draft.variableCollectionId);for(const v of all.filter(v=>v.variableCollectionId===col.id))d[v.name]=v;
const pv=Object.fromEntries(all.filter(v=>v.variableCollectionId==='VariableCollectionId:1235:17264').map(v=>[v.name,v]));
function variable(name,type,value){const v=figma.variables.createVariable(name,col,type);v.scopes=type==='BOOLEAN'?['ALL_SCOPES']:['TEXT_CONTENT'];v.setValueForMode(col.defaultModeId,value);v.hiddenFromPublishing=true;d[name]=v;return v;}
const savedSchedule=variable('savedSchedule','STRING','Today'),savedGoal=variable('savedGoal','STRING','No goal'),savedDate=variable('savedDate','STRING','None'),savedHasDate=variable('savedHasDate','BOOLEAN',false),showDraw=variable('showDrawTask','BOOLEAN',false),origin=variable('entryPoint','STRING','home'),preDate=variable('preDateGroup','STRING','Today'),goalCount=variable('goalsCount','STRING','3'),progress=variable('drawProgress','BOOLEAN',false);
const lit=(value,type)=>({type,resolvedType:type,value});const alias=v=>({type:'VARIABLE_ALIAS',resolvedType:v.resolvedType,value:{type:'VARIABLE_ALIAS',id:v.id}});const expr=(fn,args,type='BOOLEAN')=>({type:'EXPRESSION',resolvedType:type,value:{expressionFunction:fn,expressionArguments:args}});const eq=(v,value)=>expr('EQUALS',[alias(v),lit(value,v.resolvedType)]);const set=(v,value)=>({type:'SET_VARIABLE',variableId:v.id,variableValue:lit(value,v.resolvedType)});const copy=(v,from)=>({type:'SET_VARIABLE',variableId:v.id,variableValue:alias(from)});const nav=id=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:true});const iff=(condition,actions)=>({type:'CONDITIONAL',conditionalBlocks:[{condition,actions}]});
async function react(n,actions){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions}]);mutated.push(n.id);}
const origins={home:'1228:4471',tasks:'1228:4556',draw:'1239:7088'};const returnToOrigin=()=>({type:'CONDITIONAL',conditionalBlocks:[{condition:eq(origin,'tasks'),actions:[nav(origins.tasks)]},{condition:eq(origin,'draw'),actions:[nav(origins.draw)]},{actions:[nav(origins.home)]}]});
const reset=[set(d.draftSchedule,'Today'),set(d.draftDate,'None'),set(d.hasDate,false),set(d.goalFromTask,false),set(preDate,'Today')];
for(const [key,id]of Object.entries(origins)){const f=await figma.getNodeByIdAsync(id);await fonts(f);const add=f.findOne(n=>n.type==='INSTANCE'&&n.name==='New task');if(add){if(key!=='draw'){add.swapComponent(await figma.getNodeByIdAsync(M.buttonPrimary));nativeText(add,'New task');mutated.push(add.id);}await react(add,[...reset,set(d.draftGoal,key==='draw'?'Draw':'No goal'),set(origin,key),nav('1239:6412')]);}}
const emptyCancel=await figma.getNodeByIdAsync('1239:6430');await react(emptyCancel,[returnToOrigin()]);const back=await figma.getNodeByIdAsync('1239:6517');await fonts(back);nativeText(back,'Cancel');await react(back,[nav('1239:7052')]);
await react(await figma.getNodeByIdAsync('1239:7085'),[...reset,set(d.draftGoal,'No goal'),returnToOrigin()]);
// Keep the previously selected group when removing a date.
await react(await figma.getNodeByIdAsync('1239:6681'),[copy(preDate,d.draftSchedule),nav('1239:6704')]);await react(await figma.getNodeByIdAsync('1239:6804'),[set(d.draftDate,'None'),set(d.hasDate,false),copy(d.draftSchedule,preDate),nav('1239:6499')]);
// Chevron affordances live in reusable form components.
for(const id of ['1239:5907','1239:5974']){const c=await figma.getNodeByIdAsync(id);await fonts(c);for(const i of c.findAllWithCriteria({types:['INSTANCE']})){if(['Schedule','Goal'].includes(i.name)){const tr=i.findAllWithCriteria({types:['INSTANCE']}).find(x=>'Show Drill-in#212:3'in x.componentProperties);tr.setProperties({'Show Drill-in#212:3':true});mutated.push(tr.id);}}}
// Save publishes a snapshot. Draft edits remain private until Save.
const slots={};for(const group of ['Today','This Week','Someday'])slots[group]=variable('manualSlot/'+group,'BOOLEAN',false);
const updateSlots=()=>Object.keys(slots).map(group=>iff(eq(d.draftSchedule,group),Object.keys(slots).map(k=>set(slots[k],k===group))));
const countText=()=>Array.from({length:12},(_,i)=>iff(eq(pv.openTasks,i),[set(pv.openTasksText,String(i))]));
const saveActions=[iff(eq(d.taskSaved,false),[{type:'SET_VARIABLE',variableId:pv.openTasks.id,variableValue:expr('ADDITION',[alias(pv.openTasks),lit(1,'FLOAT')],'FLOAT')}]),...countText(),copy(savedSchedule,d.draftSchedule),copy(savedGoal,d.draftGoal),copy(savedDate,d.draftDate),copy(savedHasDate,d.hasDate),set(d.taskSaved,true),set(showDraw,false),iff(eq(d.draftGoal,'Draw'),[set(showDraw,true)]),...updateSlots(),returnToOrigin()];await react(await figma.getNodeByIdAsync('1239:6521'),saveActions);
const edit=[copy(d.draftSchedule,savedSchedule),copy(d.draftGoal,savedGoal),copy(d.draftDate,savedDate),copy(d.hasDate,savedHasDate)];
async function bindTask(task,key){await fonts(task);task.findOne(n=>n.name==='Schedule').setProperties({Kind:{type:'VARIABLE_ALIAS',id:savedSchedule.id}});task.findOne(n=>n.name==='Goal link').setProperties({Kind:{type:'VARIABLE_ALIAS',id:savedGoal.id}});for(const [name,to]of [['Schedule','1239:6586'],['Goal link','1239:6807'],['More actions','1239:6499']])await react(task.findOne(n=>n.name===name),[...edit,set(origin,key),nav(to)]);await react(task.findOne(n=>n.name==='Complete task'),[set(d.taskSaved,false),set(showDraw,false),...Object.values(slots).map(v=>set(v,false)),{type:'SET_VARIABLE',variableId:pv.openTasks.id,variableValue:expr('SUBTRACTION',[alias(pv.openTasks),lit(1,'FLOAT')],'FLOAT')},...countText()]);mutated.push(task.id);}
const taskOriginal=await figma.getNodeByIdAsync('1239:7183');await bindTask(taskOriginal,'tasks');const tasksBody=await figma.getNodeByIdAsync('1228:4557');
for(const group of Object.keys(slots)){const section=tasksBody.children.find(n=>n.name===group);const task=group==='Today'?taskOriginal:keep(taskOriginal.clone());section.insertChild(1,task);task.setBoundVariable('visible',slots[group]);await bindTask(task,'tasks');const date=txt(section,'',354,'Caption','Secondary');date.setBoundVariable('characters',savedDate);date.setBoundVariable('visible',savedHasDate);section.insertChild(2,date);date.visible=false;/* one date row below the task added below, scoped with the task */mutated.push(task.id);}
const homeTask=await figma.getNodeByIdAsync('1239:7162');const today=(await figma.getNodeByIdAsync('1228:4472')).children.find(n=>n.name==='Today');today.insertChild(1,homeTask);homeTask.setBoundVariable('visible',slots.Today);await bindTask(homeTask,'home');const drawTask=await figma.getNodeByIdAsync('1239:7204');drawTask.setBoundVariable('visible',showDraw);await bindTask(drawTask,'draw');
// Date details stay inside the saved task group, with visibility tied to that group's schedule.
for(const key of ['home','tasks','draw']){const f=await figma.getNodeByIdAsync(origins[key]);for(const t of f.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name==='Manually created task')){const parent=t.parent,index=parent.children.indexOf(t);const wrap=stack(parent,'Saved task and date',354,6);parent.insertChild(index,wrap);const vis=t.boundVariables.visible;if(vis)wrap.setBoundVariable('visible',await figma.variables.getVariableByIdAsync(vis.id));t.setBoundVariable('visible',null);t.visible=true;wrap.appendChild(t);const label=txt(wrap,'',338,'Caption','Secondary');label.setBoundVariable('characters',savedDate);label.setBoundVariable('visible',savedHasDate);mutated.push(t.id);}}
// Goal creation updates counts and keeps the task draft; direct creation returns to Goals.
const goalSave=await figma.getNodeByIdAsync('1239:7008');const gs=JSON.parse(JSON.stringify(goalSave.reactions[0].actions));gs.unshift(set(goalCount,'4'));await react(goalSave,gs);
for(const id of ['1228:4471','1228:4620']){const f=await figma.getNodeByIdAsync(id);for(const n of f.findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name==='Goal count'))own(n,'Count',{type:'VARIABLE_ALIAS',id:goalCount.id});}
const ge=await figma.getNodeByIdAsync('1239:6922');const gen=ge.children.find(n=>n.name==='Navigation');const spacer=gen.children.find(n=>n.name==='Trailing space');if(spacer){removed.push(spacer.id);spacer.remove();}const gsave=await inst(M.buttonPlain,gen,'Save disabled');gsave.resize(76,52);nativeText(gsave,'Save');gsave.children[0].setProperties({'Is Enabled':'False'});mutated.push(gsave.children[0].id);
// Draw progress uses its own screen and its own goal state.
const oldProgress=await figma.getNodeByIdAsync('1228:5013');await fonts(oldProgress);const entry=keep(oldProgress.clone());page.appendChild(entry);entry.name='R2 / Draw progress';entry.x=10056;entry.y=9550;for(const t of entry.findAllWithCriteria({types:['TEXT']})){if(t.characters.includes('Guitar')){t.characters=t.characters.replace(/Guitar/g,'Draw');mutated.push(t.id);}if(t.characters.includes('chord')){t.characters='Sketched for 10 minutes.';mutated.push(t.id);}}
for(const n of entry.findAll(x=>'reactions'in x&&x.reactions.length)){await react(n,[set(progress,true),nav('1239:7088')]);}
const draw=await figma.getNodeByIdAsync('1239:7088');await react(draw.findOne(n=>n.name==='Record progress'),[nav(entry.id)]);const drawBody=draw.children.find(n=>n.name==='Form content');const progressCard=await inst('1235:14564',drawBody,'Drawing progress');await fonts(progressCard);for(const t of progressCard.findAllWithCriteria({types:['TEXT']})){if(t.characters.includes('chord')||t.characters.includes('minutes')){t.characters='Sketched for 10 minutes.';mutated.push(t.id);}}progressCard.setBoundVariable('visible',progress);
// Error screen describes a failed AI attempt, regardless of the default processing fixture.
const fail=await figma.getNodeByIdAsync('1241:6529');await fonts(fail);const mode=fail.findOne(n=>n.name==='Processing');const modeText=mode.children.find(n=>n.type==='TEXT');modeText.setBoundVariable('characters',null);modeText.characters='AI processing';const editAI=mode.children.find(n=>n.type==='INSTANCE');nativeText(editAI,'AI settings');for(const i of editAI.findAllWithCriteria({types:['INSTANCE']}))if('Label#488:0'in i.componentProperties)i.setProperties({'Label#488:0':'AI settings'});mutated.push(modeText.id,editAI.id);
// Clear stale guidance bindings so the new creation buttons have a stable viewport.
for(const id of ['1228:4497','1228:4616','1228:4635']){const n=await figma.getNodeByIdAsync(id);n.setBoundVariable('visible',null);n.visible=false;mutated.push(id);}
return summary({progressScreen:entry.id,variables:Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v.id])),slotVariables:Object.fromEntries(Object.entries(slots).map(([k,v])=>[k,v.id]))});
