// Prepend common.js. Extend only the working copy.
figma.skipInvisibleInstanceChildren=false;C.Forest='#326B59';
const vars=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).filter(v=>v.variableCollectionId==='VariableCollectionId:1235:17264').map(v=>[v.name,v]));
const col=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:1235:17264');
function variable(name,type,value){const v=figma.variables.createVariable(name,col,type);v.scopes=type==='BOOLEAN'?['ALL_SCOPES']:['TEXT_CONTENT'];v.hiddenFromPublishing=true;v.setValueForMode(col.defaultModeId,value);vars[name]=v;return v;}
const goalVisible=variable('reviewGoalVisible','BOOLEAN',true),goalCount=variable('reviewGoalCount','STRING','1'),enabled=variable('reviewSaveEnabled','STRING','True'),allRemoved=variable('reviewEmpty','BOOLEAN',false);
const lit=(value,type)=>({type,resolvedType:type,value});const alias=v=>({type:'VARIABLE_ALIAS',resolvedType:v.resolvedType,value:{type:'VARIABLE_ALIAS',id:v.id}});
const expr=(fn,args)=>({type:'EXPRESSION',resolvedType:'BOOLEAN',value:{expressionFunction:fn,expressionArguments:args}});
const eq=(v,value)=>expr('EQUALS',[alias(v),lit(value,v.resolvedType)]);
const set=(v,value)=>({type:'SET_VARIABLE',variableId:v.id,variableValue:lit(value,v.resolvedType)});
const nav=id=>({type:'NODE',destinationId:id,navigation:'NAVIGATE',transition:null,resetScrollPosition:true});
async function react(n,actions){await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions}]);mutated.push(n.id);}
async function button(p,label,actions,role='Plain',w=354){const i=await inst(M['button'+role],p,label);nativeText(i,label);i.resize(w,52);await react(i,actions);return i;}
function remove(n){removed.push(n.id);n.remove();}
async function cloneScreen(id,name,x,y){const original=await figma.getNodeByIdAsync(id);await fonts(original);const f=keep(original.clone());page.appendChild(f);f.name='R2 / '+name;f.x=x;f.y=y;await f.setReactionsAsync([]);const label=txt(page,name,402,'Heading');label.x=x;label.y=y-44;return f;}
const recoveryBoard=stack(page,'Redesign Two / Recovery components',1760,24);recoveryBoard.x=13300;recoveryBoard.y=11300;recoveryBoard.paddingLeft=32;recoveryBoard.paddingRight=32;recoveryBoard.paddingTop=32;recoveryBoard.paddingBottom=32;fill(recoveryBoard,'Canvas');txt(recoveryBoard,'Keep the input. Explain the next step.',1696,'Large title');
const notices={};for(const [name,title,body]of [['Connection','Couldn’t connect','Your text is still here. Try again, or process it without AI.'],['No results','No tasks or goals found','Edit your text, or add a task yourself.'],['Voice interrupted','Recording stopped','Your transcript is still here. Continue recording or edit it before processing.']]){const c=comp(name,354,12);recoveryBoard.appendChild(c);c.name='AI2 / Recovery / '+name;c.description='Recoverable state. Preserve user input; explicit retry or alternative action. Used as an instance on the adjacent app screen.';c.paddingLeft=16;c.paddingRight=16;c.paddingTop=16;c.paddingBottom=16;fill(c,'Lilac');c.cornerRadius=20;txt(c,title,322,'Heading');txt(c,body,322,'Body','Secondary');notices[name]=c;}
const failed=await cloneScreen('1228:5227','Connection problem',8160,10600);const zero=await cloneScreen('1228:5227','No results',8634,10600);const interrupted=await cloneScreen('1228:4836','Voice interrupted',9108,10600);
for(const [f,kind]of [[failed,'Connection'],[zero,'No results']]){const b=f.children.find(n=>n.name==='Scrollable content');for(const n of [...b.children].slice(2))remove(n);const notice=await inst(notices[kind],b,kind+' notice');if(kind==='Connection'){await button(b,'Try again',[nav('1228:5247')],'Secondary');await button(b,'Use basic processing',[set(vars.processingLabel,'Basic processing'),nav('1228:5247')]);}else{await button(b,'Edit text',[nav('1228:4818')],'Secondary');await button(b,'New task',[nav('1239:6412')]);}b.itemSpacing=16;mutated.push(b.id);}
const ib=interrupted.children.find(n=>n.name==='Scrollable content');const notice=await inst(notices['Voice interrupted'],ib,'Interrupted notice');ib.insertChild(0,notice);ib.itemSpacing=24;const wave=ib.children.find(n=>n.name==='Voice waveform');wave.resize(354,100);const foot=interrupted.children.find(n=>n.name==='Primary action region');for(const n of [...foot.children])remove(n);await button(foot,'Edit text',[nav('1228:4818')],'Secondary',154);await button(foot,'Continue',[nav('1228:4836')],'Primary',188);
// Voice cancellation preserves the typed/transcribed draft rather than returning to an empty composer.
await react(await figma.getNodeByIdAsync('1228:4847'),[set(vars.hasDraft,true),nav('1228:5227')]);
// Review supports removing the goal as well as tasks; zero items disables saving.
const review=await figma.getNodeByIdAsync('1228:4532');await fonts(review);const body=review.children.find(n=>n.name==='Scrollable content');const goalSection=body.children.find(n=>n.name==='New goal');goalSection.setBoundVariable('visible',goalVisible);const rv=[vars['task/review-groceries/visible'],vars['task/review-dentist/visible'],goalVisible];
function reflect(){const a=[];for(const x of [false,true])for(const y of [false,true])for(const z of [false,true]){const count=Number(x)+Number(y)+Number(z);a.push({type:'CONDITIONAL',conditionalBlocks:[{condition:expr('AND',[expr('AND',[eq(rv[0],x),eq(rv[1],y)]),eq(rv[2],z)]),actions:[set(vars.reviewTasks,Number(x)+Number(y)),set(vars.reviewTasksText,String(Number(x)+Number(y))),set(goalCount,z?'1':'0'),set(vars.saveLabel,count?`Save ${count} ${count===1?'item':'items'}`:'Save'),set(enabled,count?'True':'False'),set(allRemoved,count===0)]}]});}return a;}
const reset=[set(rv[0],true),set(rv[1],true),set(goalVisible,true),set(vars.reviewTasks,2),set(vars.reviewTasksText,'2'),set(goalCount,'1'),set(vars.saveLabel,'Save 3 items'),set(enabled,'True'),set(allRemoved,false)];
await button(goalSection,'Remove goal',[set(goalVisible,false),...reflect()],'Plain');const empty=stack(body,'Nothing to save',354,12);empty.setBoundVariable('visible',allRemoved);txt(empty,'No items selected',354,'Title');txt(empty,'Restore the preview or edit your original text.',354,'Body','Secondary');await button(empty,'Restore preview',reset,'Secondary');await button(empty,'Edit text',[nav('1228:4818')]);body.insertChild(1,empty);
const reviewTasks=body.children.find(n=>n.name==='Tasks').findAllWithCriteria({types:['INSTANCE']}).filter(n=>n.name.startsWith('Task /'));for(const t of reviewTasks){const key=t.name.includes('dentist')?1:0;const complete=t.findOne(n=>n.name==='Complete task');if(complete)await react(complete,[set(rv[key],false),...reflect()]);}
const heading=body.children.find(n=>n.name==='Heading');const gc=heading.findAllWithCriteria({types:['INSTANCE']}).find(n=>n.name==='Goal count');if(gc)own(gc,'Count',{type:'VARIABLE_ALIAS',id:goalCount.id});
const save=await figma.getNodeByIdAsync('1228:4554');const native=save.children[0];native.setProperties({'Label#488:0':{type:'VARIABLE_ALIAS',id:vars.saveLabel.id},'Is Enabled':{type:'VARIABLE_ALIAS',id:enabled.id}});await react(save,[{type:'CONDITIONAL',conditionalBlocks:[{condition:eq(allRemoved,false),actions:[set(vars.hasDraft,false),nav('1228:4471')]}]}]);
// Every successful processing attempt begins with fresh review selections.
const processing=await figma.getNodeByIdAsync('1228:5247');await processing.setReactionsAsync([{trigger:{type:'AFTER_TIMEOUT',timeout:1.6},actions:[...reset,nav('1228:4501')]}]);mutated.push(processing.id,native.id);
// Review exit returns to the retained preview. Input remains editable.
await react(await figma.getNodeByIdAsync('1228:4550'),[nav('1228:4501')]);
const reviewMenu=await figma.getNodeByIdAsync('1228:5099');for(const i of reviewMenu.findAllWithCriteria({types:['INSTANCE']})){const name=i.componentProperties['Label#5856:123']?.value;if(name&&/remove/i.test(name)){await react(i,[{type:'CONDITIONAL',conditionalBlocks:[{condition:eq(vars.activeTask,'review-dentist'),actions:[set(rv[1],false)]},{actions:[set(rv[0],false)]}]},...reflect(),{type:'CLOSE'}]);}}
// Scenario launcher belongs to the design review, outside the product UI.
const scenarios=stack(page,'Prototype scenarios / Redesign Two',900,24);scenarios.x=10900;scenarios.y=10600;scenarios.paddingLeft=32;scenarios.paddingRight=32;scenarios.paddingTop=32;scenarios.paddingBottom=32;fill(scenarios,'Canvas');txt(scenarios,'Prototype scenarios',836,'Large title');txt(scenarios,'These buttons select simulated outcomes for design review. They are not part of Defog.',836,'Body','Secondary');
for(const [label,id,extra]of [['Create a task','1228:4471',[]],['Connection problem',failed.id,[set(vars.hasDraft,true)]],['No results',zero.id,[set(vars.hasDraft,true)]],['Interrupted voice',interrupted.id,[set(vars.hasDraft,true)]],['Microphone permission denied','1228:4997',[]],['Review with no items','1228:4532',[set(rv[0],false),set(rv[1],false),set(goalVisible,false),...reflect()]]])await button(scenarios,label,[...extra,nav(id)],'Secondary',836);
txt(recoveryBoard,'Remaining implementation work: real input and dictation; date/time selection; notification permission recovery; provider-specific errors; background/interruption handling; durable drafts and repeated-save tests. The screens above are representative proposals, not implemented guarantees.',1696,'Body','Secondary');
page.flowStartingPoints=[...page.flowStartingPoints,{nodeId:scenarios.id,name:'Redesign Two · recovery scenarios'}];
return summary({screens:{failed:failed.id,zero:zero.id,interrupted:interrupted.id},board:recoveryBoard.id,scenarios:scenarios.id,notices:Object.fromEntries(Object.entries(notices).map(([k,n])=>[k,n.id])),reviewVariables:{goalVisible:goalVisible.id,goalCount:goalCount.id,enabled:enabled.id,allRemoved:allRemoved.id}});
